-- | Go codegen over the backend-optimizer's optimized IR ('NeutralExpr').
-- |
-- | The IR we consume already has uncurrying, inlining, dead-code elimination
-- | and typed PrimOps done by the optimizer; this module turns it into Go source
-- | text (formatted afterwards by gofmt, as in Phase 1).
-- |
-- | DELIBERATE SLICE SIMPLIFICATIONS (each is a named follow-up, not an
-- | accident):
-- |
-- |   * Curried `any` runtime retained. A multi-arg `Abs [p1..pn] body` is
-- |     emitted as nested unary closures and `App f [a1..an]` as nested unary
-- |     applications -- i.e. exactly Phase 1 semantics. This is always correct
-- |     regardless of whether an application is saturated, and it is what BOTH
-- |     reference consumers do: backend-es emits `esCurriedFunction` / a folded
-- |     `EsCall hd [oneArg]` spine (Codegen/EcmaScript/Convert.purs), and purescm
-- |     emits `mkCurriedFn` / `runCurriedFn` = nested unary lambdas. Native
-- |     multi-arg is reserved for the `Uncurried*` (Fn/EffectFn) nodes below --
-- |     which we already emit natively. There is NO safe "emit native n-ary from
-- |     ordinary Abs/App" win: the optimizer's `App f args` is a syntactic spine,
-- |     not a saturation guarantee (f may be partially/over-applied), so a native
-- |     `f(a,b,c)` would be unsound.
-- |   * TCO (Stage 1): single self-recursive TOP-LEVEL functions whose optimizer
-- |     TcoRole is `isLoop` are emitted as a Go `for {}` dispatch loop (see
-- |     `loopInit`/`genStmts`) instead of stack recursion. The analysis is the
-- |     optimizer's own reusable `Codegen.Tco.analyze`. Everything else (mutual
-- |     recursion, join points, local `where go` loops, effect loops) falls
-- |     through to the curried emission, which stays correct on Go's growable
-- |     goroutine stack -- so TCO is opt-in per binding and never regresses.
-- |     Stage 2 = local LetRec/Let loops, then mutual + joins.
-- |   * PrimOps ARE lowered to native Go operators with type assertions -- that
-- |     win comes for free from the IR and needs no runtime dict.
-- |   * Effect is special-cased (EffectBind/Pure/Defer) into Go thunks.
-- |   * Hard cases not yet needed by the smoke module emit a marked panic stub
-- |     so the walk is total and surfaces exactly what each module requires.
module PureScript.Backend.Optimizer.Codegen.Go
  ( CodegenOptions
  , codegenModule
  ) where

import Prelude

import Control.Alternative (guard)
import Data.Array as Array
import Data.Array.NonEmpty (NonEmptyArray)
import Data.Array.NonEmpty as NEA
import Data.Foldable (foldMap)
import Data.Maybe (Maybe(..), fromMaybe)
import Data.Newtype (unwrap)
import Data.Number as Number
import Data.String as String
import Data.String.CodeUnits as SCU
import Data.Traversable (traverse)
import Data.Tuple (Tuple(..))
import Dodo as Dodo
import PureScript.Backend.Optimizer.Convert (BackendBindingGroup, BackendModule)
import PureScript.Backend.Optimizer.CoreFn (Ident(..), Literal(..), ModuleName(..), Prop(..), Qualified(..))
import PureScript.Backend.Optimizer.Codegen.Tco (TcoAnalysis(..), TcoExpr(..), TcoRef(..), analyze, tcoRoleIsLoop, topLevelTcoEnvGroup, topLevelTcoRefBindings)
import PureScript.Backend.Optimizer.Semantics (NeutralExpr)
import PureScript.Backend.Optimizer.Syntax (BackendAccessor(..), BackendEffect(..), BackendOperator(..), BackendOperator1(..), BackendOperator2(..), BackendOperatorNum(..), BackendOperatorOrd(..), BackendSyntax(..), Level(..), Pair(..))

type CodegenOptions = { intTags :: Boolean }

-- | Top-level entry called from Main's onCodegenModule. Builds Go source as a
-- | String and wraps it in a single Dodo text node (gofmt does the layout).
codegenModule :: forall a. CodegenOptions -> BackendModule -> Dodo.Doc a
codegenModule _ mod =
  Dodo.text $ String.joinWith "\n"
    [ "package main"
    , ""
    , "// Generated by backend-go (Phase 2, optimizer IR). Module: " <> unwrap mod.name
    , ""
    , String.joinWith "\n" (groups >>= _.decls)
    , "func init() {"
    , String.joinWith "\n" (groups >>= _.inits)
    , "}"
    ]
  where
  groups = map (genGroup mod.name) mod.bindings

-- | Emit one top-level binding group: its `var X any` decls and its `init()`
-- | assignment lines. Every binding is a memoized lazy thunk (purs $runtime_lazy
-- | analog); cyclic dictionary CAFs span modules in the whole-program build, so
-- | nothing can be eagerly ordered and references are forced on use (see genExpr
-- | Var). A single self-recursive function whose optimizer role is `isLoop` is
-- | emitted as a `for {}` dispatch loop instead of stack recursion.
genGroup :: ModuleName -> BackendBindingGroup Ident NeutralExpr -> { decls :: Array String, inits :: Array String }
genGroup mn grp = case NEA.fromArray grp.bindings of
  Nothing -> { decls: [], inits: [] }
  Just binds ->
    let
      env = if grp.recursive then topLevelTcoEnvGroup mn binds else []
      analyzed = map (\(Tuple i e) -> Tuple i (analyze env e)) binds
    in
      case if grp.recursive then loopPairs mn analyzed else Nothing of
        -- loop pairs carry their own names (incl. the synthetic internal mutual
        -- name), so derive decls from them rather than from the group idents.
        Just pairs ->
          { decls: map (\(Tuple nm _) -> "var " <> nm <> " any") pairs
          , inits: map (\(Tuple nm expr) -> nm <> " = _lazy(func() any { return " <> expr <> " })") pairs
          }
        Nothing ->
          { decls: map (\(Tuple ident _) -> "var " <> topName mn ident <> " any") (NEA.toArray binds)
          , inits: map (normalInit mn) (NEA.toArray analyzed)
          }

normalInit :: ModuleName -> Tuple Ident TcoExpr -> String
normalInit mn (Tuple ident body) =
  topName mn ident <> " = _lazy(func() any { return " <> genExpr body <> " })"

--------------------------------------------------------------------------------
-- TCO (Stage 1): single self-recursive top-level loops
--------------------------------------------------------------------------------

-- | One member of a loop group: how its (cross-/self-)calls are recognised, and
-- | its arity. A single self-recursive function is a one-member group with no
-- | branch register; a mutually-recursive group has a branch register and one
-- | member per binding.
type LoopMember = { ref :: TcoRef, arity :: Int }
type LoopCtx = { members :: Array LoopMember, regs :: Array String, branchReg :: Maybe String }

type LoopBinding =
  { ident :: Ident
  , params :: NonEmptyArray (Tuple (Maybe Ident) Level)
  , body :: TcoExpr
  }

absParams :: TcoExpr -> Maybe { params :: NonEmptyArray (Tuple (Maybe Ident) Level), body :: TcoExpr }
absParams (TcoExpr _ (Abs params body)) = Just { params, body }
absParams _ = Nothing

loopBindingOf :: Tuple Ident TcoExpr -> Maybe LoopBinding
loopBindingOf (Tuple ident e) = (\r -> { ident, params: r.params, body: r.body }) <$> absParams e

-- | A per-group unique tag for register/copy names: the first member's first
-- | param de Bruijn level. Sibling loops live in separate closures so name reuse
-- | across them is harmless; nested loops get strictly deeper levels.
loopTag :: NonEmptyArray LoopBinding -> String
loopTag members = case NEA.head (NEA.head members).params of Tuple _ (Level n) -> show n

-- | If this recursive group is one or more functions the optimizer marked
-- | `isLoop`, return the Go (name, valueExpr) pairs of its dispatch loop. For a
-- | mutually-recursive group this includes one synthetic internal-loop name plus
-- | a wrapper per member; the internal name is forced on reference like any other
-- | top-level binding (refName = `_force`).
loopPairs :: ModuleName -> NonEmptyArray (Tuple Ident TcoExpr) -> Maybe (Array (Tuple String String))
loopPairs mn analyzed = do
  refBindings <- topLevelTcoRefBindings mn analyzed
  guard (tcoRoleIsLoop refBindings)
  members <- traverse loopBindingOf analyzed
  pure $ loopBindings (topName mn) (TcoTopLevel <<< Qualified (Just mn)) (\n -> "_force(" <> n <> ")") members

-- | Build the Go (name, valueExpr) pairs for one isLoop group: a single closure
-- | for a self-recursive function, or an internal branch-dispatch loop plus one
-- | curried wrapper per member for a mutually-recursive group.
loopBindings
  :: (Ident -> String)   -- how a member ident is named in Go
  -> (Ident -> TcoRef)   -- how a member ident's calls are recognised
  -> (String -> String)  -- how to reference the synthetic internal mutual name
  -> NonEmptyArray LoopBinding
  -> Array (Tuple String String)
loopBindings nameOf refOf refName members = case NEA.toArray members of
  [ m ] -> [ Tuple (nameOf m.ident) (selfLoopClosure tag (refOf m.ident) m.params m.body) ]
  ms -> Array.cons (Tuple internalName internalFunc) (Array.mapWithIndex memberWrapper ms)
  where
  tag = loopTag members
  arities = map (NEA.length <<< _.params) (NEA.toArray members)
  maxArity = fromMaybe 1 (Array.last (Array.sort arities))
  regName i = "_r" <> tag <> "_" <> show i
  copyName i = "_c" <> tag <> "_" <> show i
  branchReg = "_br" <> tag
  branchCopy = "_brc" <> tag
  regs = map regName (Array.range 0 (maxArity - 1))
  ctx = { members: map (\m -> { ref: refOf m.ident, arity: NEA.length m.params }) (NEA.toArray members), regs, branchReg: Just branchReg }
  internalName = "_tcomut" <> tag

  internalFunc =
    let
      params = Array.cons branchCopy (map copyName (Array.range 0 (maxArity - 1)))
      regInits = Array.cons (branchReg <> " := " <> branchCopy)
        (Array.mapWithIndex (\i _ -> regName i <> " := " <> copyName i) regs)
      branches = Array.mapWithIndex branchBlock (NEA.toArray members)
    in
      "func(" <> commaSep (map (_ <> " any") params) <> ") any {\n"
        <> String.joinWith "\n" (regInits <> [ "for {" ] <> branches <> [ "}" ])
        <> "\n}"

  branchBlock idx m =
    let
      perIterBinds = Array.mapWithIndex
        (\i (Tuple mbId lvl) -> "var " <> localName mbId lvl <> " any = " <> regName i <> "\n_ = " <> localName mbId lvl)
        (NEA.toArray m.params)
    in
      "if _truthy(_intEq(" <> branchReg <> ", " <> show idx <> ")) {\n"
        <> String.joinWith "\n" (perIterBinds <> [ genStmts ctx m.body ])
        <> "\n}"

  -- f = func(p0)..(pn) { return _internal(idx, p0..pn, nil-pad to maxArity) }
  memberWrapper idx m =
    let
      ps = NEA.toArray m.params
      paramNames = map (\(Tuple mbId lvl) -> localName mbId lvl) ps
      callArgs = Array.cons (show idx) (paramNames <> Array.replicate (maxArity - Array.length ps) "nil")
      internalType = "func(" <> commaSep (Array.replicate (1 + maxArity) "any") <> ") any"
      call = refName internalName <> ".(" <> internalType <> ")(" <> commaSep callArgs <> ")"
    in
      Tuple (nameOf m.ident) (curriedReturn paramNames call)

-- | The curried-copies + register-init + for-loop closure for ONE self-recursive
-- | function. The innermost closure binds mutable registers from its param
-- | copies, then a `for {}` re-binds the real param names each iteration; a tail
-- | self-call reassigns the registers and `continue`s (no aliasing: args read the
-- | per-iteration consts, write to separate registers), a leaf `return`s.
selfLoopClosure :: String -> TcoRef -> NonEmptyArray (Tuple (Maybe Ident) Level) -> TcoExpr -> String
selfLoopClosure tag ref params body = fnExpr
  where
  ps = NEA.toArray params
  arity = Array.length ps
  regName i = "_r" <> tag <> "_" <> show i
  copyName i = "_c" <> tag <> "_" <> show i
  perIter (Tuple mbId lvl) = localName mbId lvl
  regs = Array.mapWithIndex (\i _ -> regName i) ps
  ctx = { members: [ { ref, arity } ], regs, branchReg: Nothing }
  regInits = Array.mapWithIndex (\i _ -> regName i <> " := " <> copyName i) ps
  perIterBinds = Array.mapWithIndex
    (\i p -> "var " <> perIter p <> " any = " <> regName i <> "\n_ = " <> perIter p) ps
  loopBlock = String.joinWith "\n"
    (regInits <> [ "for {" ] <> perIterBinds <> [ genStmts ctx body, "}" ])
  lastI = arity - 1
  innermost = "func(" <> copyName lastI <> " any) any {\n" <> loopBlock <> "\n}"
  outerIdxs = if arity <= 1 then [] else Array.range 0 (arity - 2)
  fnExpr = Array.foldr (\i acc -> "func(" <> copyName i <> " any) any { return " <> acc <> " }") innermost outerIdxs

-- | A curried lambda `func(p0) any { return func(p1) any { return body } }`.
curriedReturn :: Array String -> String -> String
curriedReturn params body =
  Array.foldr (\p acc -> "func(" <> p <> " any) any { return " <> acc <> " }") body params

-- | Statement-mode, tail-aware walk used only for the body of a TCO loop.
-- | A tail call to a group member becomes branch+register reassignment +
-- | `continue`; every other tail position becomes `return <expr>` (evaluated by
-- | the expression walker). Branch/Let preserve tail position into sub-bodies.
genStmts :: LoopCtx -> TcoExpr -> String
genStmts ctx te@(TcoExpr _ syn) = case syn of
  Branch pairs def ->
    String.joinWith "\n"
      ( map (\(Pair cond b) -> "if _truthy(" <> genExpr cond <> ") {\n" <> genStmts ctx b <> "\n}")
          (NEA.toArray pairs)
      )
      <> "\n" <> genStmts ctx def

  Let mbId lvl val rest ->
    let nm = localName mbId lvl
    in "var " <> nm <> " any = " <> genExpr val <> "\n_ = " <> nm <> "\n" <> genStmts ctx rest

  App (TcoExpr _ hsyn) args
    | Just idx <- findMember ctx hsyn (NEA.length args) ->
        let
          brLine = case ctx.branchReg of
            Just br -> [ br <> " = " <> show idx ]
            Nothing -> []
          regLines = Array.mapWithIndex
            (\i a -> fromMaybe "_" (Array.index ctx.regs i) <> " = " <> genExpr a)
            (NEA.toArray args)
        in String.joinWith "\n" (brLine <> regLines) <> "\ncontinue"

  _ -> "return " <> genExpr te

-- | Index of the loop member an application head refers to, if its arity matches.
findMember :: LoopCtx -> BackendSyntax TcoExpr -> Int -> Maybe Int
findMember ctx hsyn nargs =
  Array.findIndex (\m -> m.arity == nargs && matchesRef m.ref hsyn) ctx.members

isLoopAnalysis :: TcoAnalysis -> Boolean
isLoopAnalysis (TcoAnalysis a) = a.role.isLoop

matchesRef :: TcoRef -> BackendSyntax TcoExpr -> Boolean
matchesRef ref syn = case ref of
  TcoTopLevel q -> case syn of
    Var q2 -> q == q2
    _ -> false
  TcoLocal mbId lvl -> case syn of
    Local mbId2 lvl2 -> mbId == mbId2 && lvl == lvl2
    _ -> false

--------------------------------------------------------------------------------
-- Names
--------------------------------------------------------------------------------

-- | Flat-package top-level name: @Data.Maybe@ + @fromMaybe@ -> @Data_Maybe_fromMaybe@.
topName :: ModuleName -> Ident -> String
topName mn ident = goModuleName mn <> "_" <> goIdent ident

goModuleName :: ModuleName -> String
goModuleName (ModuleName mn) = String.replaceAll (String.Pattern ".") (String.Replacement "_") mn

-- | Sanitize a PureScript identifier into a Go-safe one, matching Phase 1's
-- | @CodeGen.Common.identToGoName@ EXACTLY so the names line up with the foreign
-- | shims ported from prelude.go. Char escapes mirror Phase 1; a Go-reserved
-- | word gets a trailing @_@, escaped iff its trailing-underscore-stripped CORE
-- | is reserved -- keeping the map (PS @map@ -> @map_@, foreign @map_@ ->
-- | @map__@) a bijection so distinct PS idents never collide.
goIdent :: Ident -> String
goIdent (Ident s) =
  let name = foldMap esc (SCU.toCharArray s)
      -- core = name with trailing underscores stripped
      core = SCU.fromCharArray (Array.reverse (Array.dropWhile (_ == '_') (Array.reverse (SCU.toCharArray name))))
  in if isGoReserved core then name <> "_" else name
  where
  esc c = case c of
    '\'' -> "P_"
    '$' -> "S_"
    '.' -> "_"
    '-' -> "_"
    _ ->
      if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_'
        then SCU.singleton c
        else "_u" <> SCU.singleton c -- non-ASCII-ident char; rare in our corpus

isGoReserved :: String -> Boolean
isGoReserved name = Array.elem name
  [ "break", "case", "chan", "const", "continue"
  , "default", "defer", "else", "fallthrough", "for"
  , "func", "go", "goto", "if", "import"
  , "interface", "map", "package", "range", "return"
  , "select", "struct", "switch", "type", "var"
  , "any", "nil", "true", "false", "iota"
  , "len", "cap", "make", "new", "append", "panic"
  , "string", "int", "int64", "float64", "bool", "byte", "rune"
  ]

-- | A local binder named from its de Bruijn 'Level' (optimizer guarantees
-- | uniqueness within a scope), prefixed by the source name when present for
-- | readability.
localName :: Maybe Ident -> Level -> String
localName mbIdent (Level n) = case mbIdent of
  Just (Ident s) -> "v" <> show n <> "_" <> foldMap keep (SCU.toCharArray s)
  Nothing -> "v" <> show n
  where
  keep c = if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') then SCU.singleton c else ""

--------------------------------------------------------------------------------
-- Expressions
--------------------------------------------------------------------------------

genExpr :: TcoExpr -> String
genExpr (TcoExpr ann syn) = case syn of
  -- Top-level references are forced (every top-level binding is a lazy thunk).
  Var (Qualified (Just mn) ident) -> "_force(" <> topName mn ident <> ")"
  Var (Qualified Nothing ident) -> "_force(" <> goIdent ident <> ")"

  Local mbIdent lvl -> localName mbIdent lvl

  Lit lit -> genLit lit

  -- Curried desugaring (slice): App f [a1..an] -> f(a1)(a2)..(an).
  App f args ->
    Array.foldl (\acc a -> curriedApp acc (genExpr a)) (genExpr f) (NEA.toArray args)

  -- Curried desugaring (slice): Abs [p1..pn] body -> nested unary closures.
  -- Each level returns the next closure; the innermost returns the body.
  Abs params body ->
    Array.foldr (\(Tuple mbI lvl) acc -> closure (localName mbI lvl) ("return " <> acc))
      (genExpr body)
      (NEA.toArray params)

  -- Uncurried FFI (Fn/EffectFn): real Go multi-arg funcs via variadic
  -- `func(...any) any` (matches Phase 1's _mkFn/_runFn). Calling a pure
  -- uncurried fn returns its value; an effect uncurried fn RUNS its effect on
  -- call, so its body is forced and the call site is wrapped in a thunk for
  -- uniform _runEffect.
  UncurriedAbs params body ->
    uncurriedFn (Array.fromFoldable params) (genExpr body)
  UncurriedApp f args ->
    "(" <> genExpr f <> ").(func(...any) any)(" <> commaSep (map genExpr args) <> ")"
  UncurriedEffectAbs params body ->
    uncurriedFn (Array.fromFoldable params) ("_runEffect(" <> genExpr body <> ")")
  UncurriedEffectApp f args ->
    "func() any { return (" <> genExpr f <> ").(func(...any) any)(" <> commaSep (map genExpr args) <> ") }"

  Accessor a acc -> genAccessor (genExpr a) acc

  Update _ _ -> todo "Update (record update)"

  -- Fully-applied data constructor: V{Tag, Fields}.
  CtorSaturated _ _ _ (Ident tag) fields ->
    "V{Tag: " <> goStr tag <> ", Fields: []any{" <> commaSep (map (genExpr <<< snd') fields) <> "}}"

  -- A constructor's curried builder function.
  CtorDef _ _ (Ident tag) fieldNames ->
    ctorBuilder tag fieldNames

  -- Recursive let group the optimizer marked `isLoop` (the `where go = ...`
  -- idiom, and local mutual recursion): emit a dispatch loop bound to local vars,
  -- exactly as for top-level loops but unwrapped (refName = identity, no _force).
  LetRec lvl bindings body
    | isLoopAnalysis ann
    , Just members <- traverse loopBindingOf bindings ->
        let
          pairs = loopBindings (\ident -> localName (Just ident) lvl)
            (\ident -> TcoLocal (Just ident) lvl) identity members
        in
          -- declare all names first, THEN assign: a local mutual loop's internal
          -- closure references the member wrappers (non-tail calls), and Go
          -- forbids forward-referencing a later-declared local var in a closure.
          iife
            ( map (\(Tuple nm _) -> "var " <> nm <> " any") pairs
                <> map (\(Tuple nm expr) -> nm <> " = " <> expr) pairs
                <> map (\(Tuple nm _) -> "_ = " <> nm) pairs
                <> [ "return " <> genExpr body ]
            )

  -- Non-loop recursive let group: declare all names, then assign (Go closures
  -- capture by reference, so mutual recursion resolves on the stack), then the
  -- body. All bindings share the group Level; localName disambiguates by ident.
  LetRec lvl bindings body ->
    let
      binds = NEA.toArray bindings
      nm ident = localName (Just ident) lvl
    in
      iife
        ( map (\(Tuple ident _) -> "var " <> nm ident <> " any") binds
            <> map (\(Tuple ident e) -> nm ident <> " = " <> genExpr e) binds
            <> map (\(Tuple ident _) -> "_ = " <> nm ident) binds
            <> [ "return " <> genExpr body ]
        )

  Let mbIdent lvl val body ->
    let nm = localName mbIdent lvl in
    iife
      [ "var " <> nm <> " any = " <> genExpr val
      , "_ = " <> nm  -- the optimizer may bind a value the body ignores; Go errors on unused locals
      , "return " <> genExpr body
      ]

  EffectBind mbIdent lvl val body ->
    -- Effect a == func() any. Bind sequences thunks; whole thing is a thunk.
    let nm = localName mbIdent lvl in
    "func() any {\n" <>
      "var " <> nm <> " any = _runEffect(" <> genExpr val <> ")\n" <>
      "_ = " <> nm <> "\n" <>
      "return _runEffect(" <> genExpr body <> ")\n" <>
    "}"

  EffectPure a -> "func() any { return " <> genExpr a <> " }"
  EffectDefer a -> genExpr a

  Branch pairs default_ ->
    iife (map genPair (NEA.toArray pairs) <> [ "return " <> genExpr default_ ])
    where
    genPair (Pair cond body) =
      "if _truthy(" <> genExpr cond <> ") { return " <> genExpr body <> " }"

  PrimOp op -> genOp op
  PrimEffect eff -> genPrimEffect eff
  PrimUndefined -> "nil"
  Fail msg -> "_fail(" <> goStr msg <> ")"
  where
  snd' (Tuple _ a) = a

--------------------------------------------------------------------------------
-- Literals, accessors, constructors, operators, effects
--------------------------------------------------------------------------------

genLit :: Literal TcoExpr -> String
genLit = case _ of
  LitInt n -> show n
  -- PureScript `show :: Number -> String` renders non-finite values as the
  -- bare tokens Infinity/-Infinity/NaN, which aren't valid Go float syntax.
  -- Non-finite literals reference runtime.go package vars (generated module
  -- files carry no imports; runtime.go owns the `math` import).
  LitNumber n
    | Number.isNaN n -> "_nan"
    | not (Number.isFinite n) -> if n < 0.0 then "_negInf" else "_posInf"
    | otherwise -> show n
  LitString s -> goStr s
  LitChar c -> goStr (SCU.singleton c)
  LitBoolean b -> if b then "true" else "false"
  LitArray as -> "[]any{" <> commaSep (map genExpr as) <> "}"
  LitRecord props -> "map[string]any{" <> commaSep (map genProp props) <> "}"
  where
  genProp (Prop k v) = goStr k <> ": " <> genExpr v

genAccessor :: String -> BackendAccessor -> String
genAccessor base = case _ of
  GetProp k -> "(" <> base <> ").(map[string]any)[" <> goStr k <> "]"
  GetIndex i -> "(" <> base <> ").([]any)[" <> show i <> "]"
  GetCtorField _ _ _ _ _ idx -> "(" <> base <> ").(V).Fields[" <> show idx <> "]"

genOp :: BackendOperator TcoExpr -> String
genOp = case _ of
  Op1 op a -> genOp1 op (genExpr a)
  Op2 op a b -> genOp2 op (genExpr a) (genExpr b)

-- All operators lower to `any`-taking runtime helpers (defined in runtime.go)
-- that perform their type assertions INTERNALLY. This keeps codegen uniform
-- regardless of whether an operand is concretely-typed (a literal, another
-- primop result) or boxed (a Var) -- Go forbids `.(T)` on a concrete type, so
-- inlining the assertions here would mis-emit for literal operands. Inlining
-- to native operators is a later transform-(C) concern, once we track types.
genOp1 :: BackendOperator1 -> String -> String
genOp1 op a = case op of
  OpBooleanNot -> call1 "_not" a
  OpIntBitNot -> call1 "_bitNot" a
  OpIntNegate -> call1 "_intNeg" a
  OpNumberNegate -> call1 "_numNeg" a
  OpArrayLength -> call1 "_arrayLength" a
  OpIsTag (Qualified _ (Ident tag)) -> "_isTag(" <> a <> ", " <> goStr tag <> ")"

genOp2 :: BackendOperator2 -> String -> String -> String
genOp2 op a b = case op of
  OpArrayIndex -> call2 "_arrayIndex" a b
  -- && / || MUST short-circuit: the optimizer emits e.g. `isTag Just && p(field0)`
  -- relying on the right operand not evaluating when the left is false (it would
  -- index a missing ctor field otherwise). _truthy boxes a concrete-bool operand
  -- safely, and Go's && / || skip the right operand entirely.
  OpBooleanAnd -> "(_truthy(" <> a <> ") && _truthy(" <> b <> "))"
  OpBooleanOr -> "(_truthy(" <> a <> ") || _truthy(" <> b <> "))"
  OpBooleanOrd o -> call2 ("_bool" <> ordSuffix o) a b
  OpCharOrd o -> call2 ("_char" <> ordSuffix o) a b
  OpIntBitAnd -> call2 "_bitAnd" a b
  OpIntBitOr -> call2 "_bitOr" a b
  OpIntBitShiftLeft -> call2 "_shl" a b
  OpIntBitShiftRight -> call2 "_shr" a b
  OpIntBitXor -> call2 "_bitXor" a b
  OpIntBitZeroFillShiftRight -> call2 "_zshr" a b
  OpIntNum o -> call2 ("_int" <> numSuffix o) a b
  OpIntOrd o -> call2 ("_int" <> ordSuffix o) a b
  OpNumberNum o -> call2 ("_num" <> numSuffix o) a b
  OpNumberOrd o -> call2 ("_num" <> ordSuffix o) a b
  OpStringAppend -> call2 "_strAppend" a b
  OpStringOrd o -> call2 ("_str" <> ordSuffix o) a b

ordSuffix :: BackendOperatorOrd -> String
ordSuffix = case _ of
  OpEq -> "Eq"
  OpNotEq -> "Ne"
  OpGt -> "Gt"
  OpGte -> "Ge"
  OpLt -> "Lt"
  OpLte -> "Le"

numSuffix :: BackendOperatorNum -> String
numSuffix = case _ of
  OpAdd -> "Add"
  OpSubtract -> "Sub"
  OpMultiply -> "Mul"
  OpDivide -> "Div"

call1 :: String -> String -> String
call1 fn a = fn <> "(" <> a <> ")"

call2 :: String -> String -> String -> String
call2 fn a b = fn <> "(" <> a <> ", " <> b <> ")"

genPrimEffect :: BackendEffect TcoExpr -> String
genPrimEffect = case _ of
  EffectRefNew a -> "func() any { return _refNew(" <> genExpr a <> ") }"
  EffectRefRead a -> "func() any { return _refRead(" <> genExpr a <> ") }"
  EffectRefWrite a b -> "func() any { return _refWrite(" <> genExpr a <> ", " <> genExpr b <> ") }"

--------------------------------------------------------------------------------
-- Go emission helpers
--------------------------------------------------------------------------------

-- | Curried unary application: f.(func(any) any)(x).
curriedApp :: String -> String -> String
curriedApp f x = "(" <> f <> ").(func(any) any)(" <> x <> ")"

closure :: String -> String -> String
closure param body = "func(" <> param <> " any) any {\n" <> body <> "\n}"

-- | A variadic uncurried function: binds each param from _args[i], then returns
-- | the given expression. Used for Fn/EffectFn (UncurriedAbs/UncurriedEffectAbs).
uncurriedFn :: Array (Tuple (Maybe Ident) Level) -> String -> String
uncurriedFn params retExpr =
  "func(_args ...any) any {\n"
    <> String.joinWith "\n" (Array.mapWithIndex bindParam params <> [ "return " <> retExpr ])
    <> "\n}"
  where
  bindParam i (Tuple mbI lvl) =
    let nm = localName mbI lvl in "var " <> nm <> " any = _args[" <> show i <> "]\n_ = " <> nm

iife :: Array String -> String
iife stmts = "func() any {\n" <> String.joinWith "\n" stmts <> "\n}()"

ctorBuilder :: String -> Array String -> String
ctorBuilder tag fieldNames =
  Array.foldr (\f acc -> closure ("f_" <> f) ("return " <> acc)) ctorVal fieldNames
  where
  ctorVal = "V{Tag: " <> goStr tag <> ", Fields: []any{" <> commaSep (map (\f -> "f_" <> f) fieldNames) <> "}}"

goStr :: String -> String
goStr s = "\"" <> foldMap escapeChar (SCU.toCharArray s) <> "\""
  where
  escapeChar c = case c of
    '"' -> "\\\""
    '\\' -> "\\\\"
    '\n' -> "\\n"
    '\t' -> "\\t"
    '\r' -> "\\r"
    _ -> SCU.singleton c

commaSep :: Array String -> String
commaSep = String.joinWith ", "

todo :: String -> String
todo what = "_todo(" <> goStr what <> ")"
