-- | Go codegen over the backend-optimizer's optimized IR ('NeutralExpr').
-- |
-- | First vertical slice (branch phase2-backend-optimizer). The IR we consume
-- | already has uncurrying, inlining, dead-code elimination and typed PrimOps
-- | done by the optimizer; this module turns it into Go source text (formatted
-- | afterwards by gofmt, as in Phase 1).
-- |
-- | DELIBERATE SLICE SIMPLIFICATIONS (each is a named follow-up, not an
-- | accident):
-- |
-- |   * Curried `any` runtime retained. A multi-arg `Abs [p1..pn] body` is
-- |     emitted as nested unary closures and `App f [a1..an]` as nested unary
-- |     applications -- i.e. exactly Phase 1 semantics. This is always correct
-- |     regardless of whether an application is saturated. Emitting native Go
-- |     multi-arg functions (the real Stage 2a uncurrying win) is the next step,
-- |     gated on the conformance corpus.
-- |   * PrimOps ARE lowered to native Go operators with type assertions -- that
-- |     win comes for free from the IR and needs no runtime dict.
-- |   * Effect is special-cased (EffectBind/Pure/Defer) into Go thunks.
-- |   * Hard cases not yet needed by the smoke module emit a marked panic stub
-- |     so the walk is total and surfaces exactly what each module requires.
module PureScript.Backend.Optimizer.Codegen.Go
  ( CodegenOptions
  , codegenModule
  ) where

import Prelude

import Data.Array as Array
import Data.Array.NonEmpty as NEA
import Data.Foldable (foldMap)
import Data.Maybe (Maybe(..))
import Data.Newtype (unwrap)
import Data.String as String
import Data.String.CodeUnits as SCU
import Data.Tuple (Tuple(..))
import Dodo as Dodo
import PureScript.Backend.Optimizer.Convert (BackendModule)
import PureScript.Backend.Optimizer.CoreFn (Ident(..), Literal(..), ModuleName(..), Prop(..), Qualified(..))
import PureScript.Backend.Optimizer.Semantics (NeutralExpr(..))
import PureScript.Backend.Optimizer.Syntax (BackendAccessor(..), BackendEffect(..), BackendOperator(..), BackendOperator1(..), BackendOperator2(..), BackendOperatorNum(..), BackendOperatorOrd(..), BackendSyntax(..), Level(..), Pair(..))

type CodegenOptions = { intTags :: Boolean }

-- | Top-level entry called from Main's onCodegenModule. Builds Go source as a
-- | String and wraps it in a single Dodo text node (gofmt does the layout).
codegenModule :: forall a. CodegenOptions -> BackendModule -> Dodo.Doc a
codegenModule _ mod =
  Dodo.text $ String.joinWith "\n"
    [ "package main"
    , ""
    , "// Generated by backend-go (Phase 2, optimizer IR). Module: " <> unwrap mod.name
    , ""
    , declSection
    , initSection
    ]
  where
  flatBindings :: Array (Tuple Ident NeutralExpr)
  flatBindings = mod.bindings >>= _.bindings

  declSection :: String
  declSection = String.joinWith "\n"
    (map (\(Tuple ident _) -> "var " <> topName mod.name ident <> " any") flatBindings)

  initSection :: String
  initSection = String.joinWith "\n"
    ( [ "func init() {" ]
        <> map assignLine flatBindings
        <> [ "}" ]
    )
    where
    assignLine (Tuple ident expr) =
      topName mod.name ident <> " = " <> genExpr expr

--------------------------------------------------------------------------------
-- Names
--------------------------------------------------------------------------------

-- | Flat-package top-level name: @Data.Maybe@ + @fromMaybe@ -> @Data_Maybe_fromMaybe@.
topName :: ModuleName -> Ident -> String
topName mn ident = goModuleName mn <> "_" <> goIdent ident

goModuleName :: ModuleName -> String
goModuleName (ModuleName mn) = String.replaceAll (String.Pattern ".") (String.Replacement "_") mn

-- | Sanitize a PureScript identifier into a Go-safe one. Minimal for the slice;
-- | the Phase 1 bijective mangler (reserved-word escaping) is a follow-up.
goIdent :: Ident -> String
goIdent (Ident s) = foldMap esc (SCU.toCharArray s)
  where
  esc c = case c of
    '\'' -> "P_"
    '$' -> "S_"
    '.' -> "_"
    _ -> SCU.singleton c

-- | A local binder named from its de Bruijn 'Level' (optimizer guarantees
-- | uniqueness within a scope), prefixed by the source name when present for
-- | readability.
localName :: Maybe Ident -> Level -> String
localName mbIdent (Level n) = case mbIdent of
  Just (Ident s) -> "v" <> show n <> "_" <> foldMap keep (SCU.toCharArray s)
  Nothing -> "v" <> show n
  where
  keep c = if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') then SCU.singleton c else ""

--------------------------------------------------------------------------------
-- Expressions
--------------------------------------------------------------------------------

genExpr :: NeutralExpr -> String
genExpr (NeutralExpr syn) = case syn of
  Var (Qualified (Just mn) ident) -> topName mn ident
  Var (Qualified Nothing ident) -> goIdent ident

  Local mbIdent lvl -> localName mbIdent lvl

  Lit lit -> genLit lit

  -- Curried desugaring (slice): App f [a1..an] -> f(a1)(a2)..(an).
  App f args ->
    Array.foldl (\acc a -> curriedApp acc (genExpr a)) (genExpr f) (NEA.toArray args)

  -- Curried desugaring (slice): Abs [p1..pn] body -> nested unary closures.
  -- Each level returns the next closure; the innermost returns the body.
  Abs params body ->
    Array.foldr (\(Tuple mbI lvl) acc -> closure (localName mbI lvl) ("return " <> acc))
      (genExpr body)
      (NEA.toArray params)

  -- Uncurried FFI (Fn/EffectFn). Follow-up: emit real Go multi-arg funcs/calls.
  UncurriedApp _ _ -> todo "UncurriedApp"
  UncurriedAbs _ _ -> todo "UncurriedAbs"
  UncurriedEffectApp _ _ -> todo "UncurriedEffectApp"
  UncurriedEffectAbs _ _ -> todo "UncurriedEffectAbs"

  Accessor a acc -> genAccessor (genExpr a) acc

  Update _ _ -> todo "Update (record update)"

  -- Fully-applied data constructor: V{Tag, Fields}.
  CtorSaturated _ _ _ (Ident tag) fields ->
    "V{Tag: " <> goStr tag <> ", Fields: []any{" <> commaSep (map (genExpr <<< snd') fields) <> "}}"

  -- A constructor's curried builder function.
  CtorDef _ _ (Ident tag) fieldNames ->
    ctorBuilder tag fieldNames

  LetRec _ _ _ -> todo "LetRec"

  Let mbIdent lvl val body ->
    iife
      [ "var " <> localName mbIdent lvl <> " any = " <> genExpr val
      , "return " <> genExpr body
      ]

  EffectBind mbIdent lvl val body ->
    -- Effect a == func() any. Bind sequences thunks; whole thing is a thunk.
    "func() any {\n" <>
      "var " <> localName mbIdent lvl <> " any = _runEffect(" <> genExpr val <> ")\n" <>
      "return _runEffect(" <> genExpr body <> ")\n" <>
    "}"

  EffectPure a -> "func() any { return " <> genExpr a <> " }"
  EffectDefer a -> genExpr a

  Branch pairs default_ ->
    iife (map genPair (NEA.toArray pairs) <> [ "return " <> genExpr default_ ])
    where
    genPair (Pair cond body) =
      "if _truthy(" <> genExpr cond <> ") { return " <> genExpr body <> " }"

  PrimOp op -> genOp op
  PrimEffect eff -> genPrimEffect eff
  PrimUndefined -> "nil"
  Fail msg -> "_fail(" <> goStr msg <> ")"
  where
  snd' (Tuple _ a) = a

--------------------------------------------------------------------------------
-- Literals, accessors, constructors, operators, effects
--------------------------------------------------------------------------------

genLit :: Literal NeutralExpr -> String
genLit = case _ of
  LitInt n -> show n
  LitNumber n -> show n
  LitString s -> goStr s
  LitChar c -> goStr (SCU.singleton c)
  LitBoolean b -> if b then "true" else "false"
  LitArray as -> "[]any{" <> commaSep (map genExpr as) <> "}"
  LitRecord props -> "map[string]any{" <> commaSep (map genProp props) <> "}"
  where
  genProp (Prop k v) = goStr k <> ": " <> genExpr v

genAccessor :: String -> BackendAccessor -> String
genAccessor base = case _ of
  GetProp k -> "(" <> base <> ").(map[string]any)[" <> goStr k <> "]"
  GetIndex i -> "(" <> base <> ").([]any)[" <> show i <> "]"
  GetCtorField _ _ _ _ _ idx -> "(" <> base <> ").(V).Fields[" <> show idx <> "]"

genOp :: BackendOperator NeutralExpr -> String
genOp = case _ of
  Op1 op a -> genOp1 op (genExpr a)
  Op2 op a b -> genOp2 op (genExpr a) (genExpr b)

-- All operators lower to `any`-taking runtime helpers (defined in runtime.go)
-- that perform their type assertions INTERNALLY. This keeps codegen uniform
-- regardless of whether an operand is concretely-typed (a literal, another
-- primop result) or boxed (a Var) -- Go forbids `.(T)` on a concrete type, so
-- inlining the assertions here would mis-emit for literal operands. Inlining
-- to native operators is a later transform-(C) concern, once we track types.
genOp1 :: BackendOperator1 -> String -> String
genOp1 op a = case op of
  OpBooleanNot -> call1 "_not" a
  OpIntBitNot -> call1 "_bitNot" a
  OpIntNegate -> call1 "_intNeg" a
  OpNumberNegate -> call1 "_numNeg" a
  OpArrayLength -> call1 "_arrayLength" a
  OpIsTag (Qualified _ (Ident tag)) -> "_isTag(" <> a <> ", " <> goStr tag <> ")"

genOp2 :: BackendOperator2 -> String -> String -> String
genOp2 op a b = case op of
  OpArrayIndex -> call2 "_arrayIndex" a b
  OpBooleanAnd -> call2 "_and" a b
  OpBooleanOr -> call2 "_or" a b
  OpBooleanOrd o -> call2 ("_bool" <> ordSuffix o) a b
  OpCharOrd o -> call2 ("_char" <> ordSuffix o) a b
  OpIntBitAnd -> call2 "_bitAnd" a b
  OpIntBitOr -> call2 "_bitOr" a b
  OpIntBitShiftLeft -> call2 "_shl" a b
  OpIntBitShiftRight -> call2 "_shr" a b
  OpIntBitXor -> call2 "_bitXor" a b
  OpIntBitZeroFillShiftRight -> call2 "_zshr" a b
  OpIntNum o -> call2 ("_int" <> numSuffix o) a b
  OpIntOrd o -> call2 ("_int" <> ordSuffix o) a b
  OpNumberNum o -> call2 ("_num" <> numSuffix o) a b
  OpNumberOrd o -> call2 ("_num" <> ordSuffix o) a b
  OpStringAppend -> call2 "_strAppend" a b
  OpStringOrd o -> call2 ("_str" <> ordSuffix o) a b

ordSuffix :: BackendOperatorOrd -> String
ordSuffix = case _ of
  OpEq -> "Eq"
  OpNotEq -> "Ne"
  OpGt -> "Gt"
  OpGte -> "Ge"
  OpLt -> "Lt"
  OpLte -> "Le"

numSuffix :: BackendOperatorNum -> String
numSuffix = case _ of
  OpAdd -> "Add"
  OpSubtract -> "Sub"
  OpMultiply -> "Mul"
  OpDivide -> "Div"

call1 :: String -> String -> String
call1 fn a = fn <> "(" <> a <> ")"

call2 :: String -> String -> String -> String
call2 fn a b = fn <> "(" <> a <> ", " <> b <> ")"

genPrimEffect :: BackendEffect NeutralExpr -> String
genPrimEffect = case _ of
  EffectRefNew a -> "func() any { return _refNew(" <> genExpr a <> ") }"
  EffectRefRead a -> "func() any { return _refRead(" <> genExpr a <> ") }"
  EffectRefWrite a b -> "func() any { return _refWrite(" <> genExpr a <> ", " <> genExpr b <> ") }"

--------------------------------------------------------------------------------
-- Go emission helpers
--------------------------------------------------------------------------------

-- | Curried unary application: f.(func(any) any)(x).
curriedApp :: String -> String -> String
curriedApp f x = "(" <> f <> ").(func(any) any)(" <> x <> ")"

closure :: String -> String -> String
closure param body = "func(" <> param <> " any) any {\n" <> body <> "\n}"

iife :: Array String -> String
iife stmts = "func() any {\n" <> String.joinWith "\n" stmts <> "\n}()"

ctorBuilder :: String -> Array String -> String
ctorBuilder tag fieldNames =
  Array.foldr (\f acc -> closure ("f_" <> f) ("return " <> acc)) ctorVal fieldNames
  where
  ctorVal = "V{Tag: " <> goStr tag <> ", Fields: []any{" <> commaSep (map (\f -> "f_" <> f) fieldNames) <> "}}"

goStr :: String -> String
goStr s = "\"" <> foldMap escapeChar (SCU.toCharArray s) <> "\""
  where
  escapeChar c = case c of
    '"' -> "\\\""
    '\\' -> "\\\\"
    '\n' -> "\\n"
    '\t' -> "\\t"
    '\r' -> "\\r"
    _ -> SCU.singleton c

commaSep :: Array String -> String
commaSep = String.joinWith ", "

todo :: String -> String
todo what = "_todo(" <> goStr what <> ")"
