module Main where

import Prelude

import ArgParse.Basic (ArgParser)
import ArgParse.Basic as ArgParser
import Data.Array as Array
import Data.Either (Either(..))
import Data.Map as Map
import Data.Maybe (Maybe(..))
import Data.Set as Set
import Data.String as String
import Data.Traversable (for_)
import Dodo as Dodo
import Effect (Effect)
import Effect.Aff (Aff, launchAff_)
import Effect.Class (liftEffect)
import Effect.Class.Console as Console
import Effect.Ref as Ref
import Node.Encoding (Encoding(..))
import Node.FS.Aff as FS
import Node.FS.Perms as Perms
import Node.Path (FilePath)
import Node.Path as Path
import Node.Process as Process
import PureScript.Backend.Optimizer.Codegen.Go (codegenModule)
import PureScript.Backend.Optimizer.Codegen.Go.Builder (basicBuildMain)
import PureScript.Backend.Optimizer.CoreFn (Ident(..), ModuleName(..), Qualified(..))
import PureScript.Backend.Optimizer.Reachability (pruneModule, reachableFromEntry)
import PureScript.Backend.Optimizer.Semantics.Foreign (coreForeignSemantics)

type BuildArgs =
  { coreFnDir :: FilePath
  , outputDir :: FilePath
  , mainModule :: String
  }

argParser :: ArgParser BuildArgs
argParser =
  ArgParser.fromRecord
    { coreFnDir:
        ArgParser.argument [ "--corefn-dir" ]
          "Path to input directory containing corefn.json files (default ./output)."
          # ArgParser.default (Path.concat [ ".", "output" ])
    , outputDir:
        ArgParser.argument [ "--output-dir" ]
          "Path to output directory for Go files (default ./output-go-opt)."
          # ArgParser.default (Path.concat [ ".", "output-go-opt" ])
    , mainModule:
        ArgParser.argument [ "--main" ]
          "Entry module whose `main :: Effect _` is run (default Main)."
          # ArgParser.default "Main"
    }
    <* ArgParser.flagHelp

main :: Effect Unit
main = do
  args <- Array.drop 2 <$> Process.argv
  case ArgParser.parseArgs "backend-go" "PureScript Go backend (optimizer IR)." argParser args of
    Left err -> Console.error (ArgParser.printArgError err)
    Right buildArgs -> launchAff_ (build buildArgs)

build :: BuildArgs -> Aff Unit
build args = do
  -- Accumulate every built module, then in onCodegenAfter compute reachability
  -- from `main` and emit only the reachable bindings. Pruning needs the global
  -- reference graph, so we can't emit per-module as we go.
  modulesRef <- liftEffect (Ref.new [])
  basicBuildMain
    { resolveCoreFnDirectory: pure args.coreFnDir
    , resolveExternalDirectives: pure Map.empty
    , analyzeCustom: \_ _ -> Nothing
    , foreignSemantics: coreForeignSemantics
    , onCodegenBefore: mkdirp args.outputDir
    , onPrepareModule: \_ coreFnMod -> pure coreFnMod
    , onCodegenModule: \_ _ backendMod _ ->
        liftEffect (Ref.modify_ (_ <> [ backendMod ]) modulesRef)
    , onCodegenAfter: do
        modules <- liftEffect (Ref.read modulesRef)
        let
          entry = Qualified (Just (ModuleName args.mainModule)) (Ident "main")
          reachable = reachableFromEntry entry modules
        -- emit only modules with a reachable binding, each pruned to its reachable set
        for_ modules \backendMod ->
          case pruneModule reachable backendMod of
            Nothing -> pure unit
            Just pruned -> do
              let
                ModuleName name = pruned.name
                formatted = Dodo.print Dodo.plainText Dodo.twoSpaces (codegenModule { intTags: false } pruned)
                fileName = String.replaceAll (String.Pattern ".") (String.Replacement "_") name <> ".go"
              FS.writeTextFile UTF8 (Path.concat [ args.outputDir, fileName ]) formatted
        let
          entryName = String.replaceAll (String.Pattern ".") (String.Replacement "_") args.mainModule
          entryGo = String.joinWith "\n"
            [ "package main"
            , ""
            , "// Entry point generated by backend-go for module " <> args.mainModule
            , "func main() {"
            , "\t_runEffect(_force(" <> entryName <> "_main))"
            , "}"
            , ""
            ]
        -- NB: not "_entry.go" — the Go toolchain ignores files starting with "_".
        FS.writeTextFile UTF8 (Path.concat [ args.outputDir, "entrypoint.go" ]) entryGo
    , traceIdents: Set.empty
    }

mkdirp :: FilePath -> Aff Unit
mkdirp = flip FS.mkdir' { recursive: true, mode: Perms.mkPerms Perms.all Perms.all Perms.all }
