// Generated by psgo: static runtime + foreign-shim catalogue. Do not edit
// the emitted copy; edit purescript-go/runtime/prelude.go (embedded into psgo).
//
// ADR-0001: everything is `any`; functions are curried unary closures
// (application is `f.(func(any) any)(x)`); ADTs are V{Tag,Fields}; records and
// typeclass dicts are map[string]any; Effect a is a `func() any` thunk; Unit is
// nil. ADR-0005: core stdlib shims MAY encode that representation; each mirrors
// the real JS foreign in output/<Module>/foreign.js. Int is Go `int` and String
// is UTF-8, so this inherits Julia's INT64/ASTRAL divergence ledger verbatim
// (e.g. intAdd does NOT wrap to int32 the way the JS `| 0` does).
package main

import (
	"fmt"
	"math"
	"os"
	"regexp"
	"strconv"
	"strings"
	"sync"
)

// ---------------------------------------------------------------------------
// runtime
// ---------------------------------------------------------------------------

// V is the universal ADT value: a tag plus its fields.
type V struct {
	Tag    string
	Fields []any
}

func _b2i(b bool) int {
	if b {
		return 1
	}
	return 0
}

// _lazy wraps a generated top-level binding's initializer in a memoized thunk.
// Every generated binding is emitted as `var X any` assigned `_lazy(func() any
// { return <init> })`, and every reference to a generated binding is forced via
// _force(X). This defers all initialization to first use, so the cyclic
// typeclass-dictionary clusters (whose cycle edges are lazy `\_ -> dict`
// closures) resolve on demand regardless of declaration order -- the Go analogue
// of purs's `$runtime_lazy`.
//
// backend-go change vs Phase 1: codegen forces EVERY top-level Var reference
// (per-module codegen can't cheaply know whether a name is a generated binding
// or a foreign/runtime shim). So thunks carry a DISTINCT type and _force passes
// non-thunks (the direct-value foreign shims below) through untouched. That
// also disambiguates a lazy thunk from an `Effect a` value -- both would
// otherwise be `func() any`.
//
// CONCURRENCY: forcing is guarded by a per-thunk sync.Once, so a CAF shared
// across goroutines (the `bosun serve` / any concurrent-server case) is forced
// at most once and read race-free; the prior unsynchronized done/forcing/val
// dance was a data race AND could spuriously panic. The Once does memoize-once
// and mutual-exclusion in one. Tradeoff vs the old `forcing` flag: a GENUINE
// eager self-referential strict cycle now DEADLOCKS (re-entrant Once on one
// goroutine) instead of panicking. That input has no valid value either way,
// and backend-go does not emit it — legitimate cyclic typeclass-dict clusters
// break their cycles with deferred lazy `\_ -> dict` edges (no synchronous
// re-force). The one place a deadlock is worse than a panic — a single hung
// goroutine in a resident server, which Go's deadlock detector can't see — is
// owned at the serve layer via request/handler timeouts, not here.
type _thunk struct {
	once sync.Once
	val  any
	fn   func() any
}

func _lazy(fn func() any) any {
	return &_thunk{fn: fn}
}

// _force evaluates a generated binding's memoized thunk; a direct value (any
// foreign/runtime shim) is returned as-is. Thread-safe and forced-once.
func _force(x any) any {
	t, ok := x.(*_thunk)
	if !ok {
		return x
	}
	t.once.Do(func() {
		t.val = t.fn()
		t.fn = nil
	})
	return t.val
}

// _mkOrd builds an unsafeCompareImpl-shaped shim from a typed 3-way compare:
// ordXImpl(lt)(eq)(gt)(x)(y) -> lt | eq | gt.
func _mkOrd(cmp func(x, y any) int) any {
	return func(lt any) any {
		return func(eq any) any {
			return func(gt any) any {
				return func(x any) any {
					return func(y any) any {
						c := cmp(x, y)
						if c < 0 {
							return lt
						}
						if c == 0 {
							return eq
						}
						return gt
					}
				}
			}
		}
	}
}

// _floorDivPos is floor division for a positive divisor (Go / truncates toward
// zero; JS intDiv uses Math.floor).
func _floorDivPos(x, y int) int {
	q := x / y
	if x%y != 0 && (x < 0) != (y < 0) {
		q--
	}
	return q
}

func _showInt(n int) string { return strconv.Itoa(n) }

// _jsNumToString mirrors ECMAScript Number::toString (spec 6.1.6.1.20) for a
// finite value. Go's strconv 'g' format uses different exponent thresholds and
// zero-pads exponents ("1e-06" vs JS "1e-6"), so we take the shortest
// round-trip digits + decimal exponent from strconv's 'e' format and reformat
// per the JS rules: fixed notation for -6 < n <= 21, exponential otherwise,
// with a sign-only (unpadded) exponent.
func _jsNumToString(f float64) string {
	if f == 0 {
		return "0" // covers +0 and -0 (JS (-0).toString() === "0")
	}
	neg := f < 0
	if neg {
		f = -f
	}
	e := strconv.FormatFloat(f, 'e', -1, 64) // "d.ddde±XX" or "de±XX"
	ei := strings.IndexByte(e, 'e')
	exp, _ := strconv.Atoi(e[ei+1:])
	digits := strings.Replace(e[:ei], ".", "", 1)
	k := len(digits) // number of significant digits
	n := exp + 1     // position of the decimal point (value = digits x 10^(n-k))
	var s string
	switch {
	case k <= n && n <= 21:
		s = digits + strings.Repeat("0", n-k)
	case 0 < n && n <= 21:
		s = digits[:n] + "." + digits[n:]
	case -6 < n && n <= 0:
		s = "0." + strings.Repeat("0", -n) + digits
	default:
		mant := digits
		if k > 1 {
			mant = digits[:1] + "." + digits[1:]
		}
		ev := n - 1
		sign := "+"
		if ev < 0 {
			sign = "-"
			ev = -ev
		}
		s = mant + "e" + sign + strconv.Itoa(ev)
	}
	if neg {
		s = "-" + s
	}
	return s
}

func _showNumber(f float64) string {
	if math.IsNaN(f) {
		return "NaN"
	}
	if math.IsInf(f, 1) {
		return "Infinity"
	}
	if math.IsInf(f, -1) {
		return "-Infinity"
	}
	s := _jsNumToString(f)
	// showNumberImpl appends ".0" iff str+".0" still parses as a number -- i.e.
	// only for plain-integer renderings (no '.', 'e', or 'E').
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

// JS bitwise ops coerce operands and result through ToInt32 / ToUint32.
func _toInt32(x int) int  { return int(int32(uint32(x))) }
func _toUint32(x int) int { return int(uint32(x)) }

// Shared stable merge sort (Data.Array.sortByImpl + Data.Array.ST.sortByImpl).
// compare returns an Ordering ADT; fromOrdering maps it to an int (-1/0/1).
// xs1 is written; xs2 is scratch. Mirrors the JS mergeFromTo verbatim.
func _mergeFromTo(compare, fromOrdering func(any) any, xs1, xs2 []any, from, to int) {
	mid := from + ((to - from) >> 1)
	if mid-from > 1 {
		_mergeFromTo(compare, fromOrdering, xs2, xs1, from, mid)
	}
	if to-mid > 1 {
		_mergeFromTo(compare, fromOrdering, xs2, xs1, mid, to)
	}
	i, j, k := from, mid, from
	for i < mid && j < to {
		x, y := xs2[i], xs2[j]
		c := fromOrdering(compare(x).(func(any) any)(y)).(int)
		if c > 0 {
			xs1[k] = y
			k++
			j++
		} else {
			xs1[k] = x
			k++
			i++
		}
	}
	for i < mid {
		xs1[k] = xs2[i]
		k++
		i++
	}
	for j < to {
		xs1[k] = xs2[j]
		k++
		j++
	}
}

// Identity sentinel for the cons-list built by Data.Array.fromFoldableImpl.
type _consNil struct{}

var _flEmpty any = &_consNil{}

func _showChar(cs string) string {
	rs := []rune(cs)
	if len(rs) == 0 {
		return "''"
	}
	code := int(rs[0])
	if code < 0x20 || code == 0x7F {
		switch code {
		case 0x07:
			return "'\\a'"
		case 0x08:
			return "'\\b'"
		case 0x0C:
			return "'\\f'"
		case 0x0A:
			return "'\\n'"
		case 0x0D:
			return "'\\r'"
		case 0x09:
			return "'\\t'"
		case 0x0B:
			return "'\\v'"
		}
		return "'\\" + strconv.Itoa(code) + "'"
	}
	if cs == "'" || cs == "\\" {
		return "'\\" + cs + "'"
	}
	return "'" + cs + "'"
}

func _showString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	rs := []rune(s)
	for i := 0; i < len(rs); i++ {
		c := rs[i]
		code := int(c)
		if code <= 0x1F || code == 0x7F || c == '"' || c == '\\' {
			switch c {
			case '"':
				b.WriteString("\\\"")
			case '\\':
				b.WriteString("\\\\")
			case 0x07:
				b.WriteString("\\a")
			case 0x08:
				b.WriteString("\\b")
			case 0x0C:
				b.WriteString("\\f")
			case 0x0A:
				b.WriteString("\\n")
			case 0x0D:
				b.WriteString("\\r")
			case 0x09:
				b.WriteString("\\t")
			case 0x0B:
				b.WriteString("\\v")
			default:
				empty := ""
				if i+1 < len(rs) && rs[i+1] >= '0' && rs[i+1] <= '9' {
					empty = "\\&"
				}
				b.WriteString("\\" + strconv.Itoa(code) + empty)
			}
		} else {
			b.WriteRune(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// _refEq: structural == on comparable dynamic types (int/string/bool/float64,
// and single-char strings standing in for Char). Mirrors JS `r1 === r2`.
var _refEq any = func(a any) any {
	return func(b any) any {
		return a == b
	}
}

// ---------------------------------------------------------------------------
// Data.Unit / Unsafe.Coerce / Data.Symbol / Record.Unsafe
// ---------------------------------------------------------------------------

var Data_Unit_unit any = nil

var Unsafe_Coerce_unsafeCoerce any = func(x any) any { return x }
var Data_Symbol_unsafeCoerce any = func(x any) any { return x }

var Record_Unsafe_unsafeGet any = func(label any) any {
	return func(rec any) any {
		return rec.(map[string]any)[label.(string)]
	}
}

var Record_Unsafe_unsafeSet any = func(label any) any {
	return func(value any) any {
		return func(rec any) any {
			out := map[string]any{}
			for k, v := range rec.(map[string]any) {
				out[k] = v
			}
			out[label.(string)] = value
			return out
		}
	}
}

// ---------------------------------------------------------------------------
// Data.Semiring / Data.Ring / Data.EuclideanRing  (INT64 ledger: no int32 wrap)
// ---------------------------------------------------------------------------

var Data_Semiring_intAdd any = func(a any) any { return func(b any) any { return a.(int) + b.(int) } }
var Data_Semiring_intMul any = func(a any) any { return func(b any) any { return a.(int) * b.(int) } }
var Data_Semiring_numAdd any = func(a any) any { return func(b any) any { return a.(float64) + b.(float64) } }
var Data_Semiring_numMul any = func(a any) any { return func(b any) any { return a.(float64) * b.(float64) } }

var Data_Ring_intSub any = func(a any) any { return func(b any) any { return a.(int) - b.(int) } }
var Data_Ring_numSub any = func(a any) any { return func(b any) any { return a.(float64) - b.(float64) } }

var Data_EuclideanRing_intDegree any = func(x any) any {
	n := x.(int)
	if n < 0 {
		n = -n
	}
	if n > 2147483647 {
		n = 2147483647
	}
	return n
}
var Data_EuclideanRing_intDiv any = func(x any) any {
	return func(y any) any {
		a, b := x.(int), y.(int)
		if b == 0 {
			return 0
		}
		if b > 0 {
			return _floorDivPos(a, b)
		}
		return -_floorDivPos(a, -b)
	}
}
var Data_EuclideanRing_intMod any = func(x any) any {
	return func(y any) any {
		a, b := x.(int), y.(int)
		if b == 0 {
			return 0
		}
		if b < 0 {
			b = -b
		}
		return ((a % b) + b) % b
	}
}
var Data_EuclideanRing_numDiv any = func(a any) any { return func(b any) any { return a.(float64) / b.(float64) } }

// ---------------------------------------------------------------------------
// Data.HeytingAlgebra
// ---------------------------------------------------------------------------

var Data_HeytingAlgebra_boolConj any = func(a any) any { return func(b any) any { return a.(bool) && b.(bool) } }
var Data_HeytingAlgebra_boolDisj any = func(a any) any { return func(b any) any { return a.(bool) || b.(bool) } }
var Data_HeytingAlgebra_boolNot any = func(a any) any { return !a.(bool) }

// ---------------------------------------------------------------------------
// Data.Eq
// ---------------------------------------------------------------------------

var Data_Eq_eqBooleanImpl any = _refEq
var Data_Eq_eqIntImpl any = _refEq
var Data_Eq_eqNumberImpl any = _refEq
var Data_Eq_eqCharImpl any = _refEq
var Data_Eq_eqStringImpl any = _refEq

var Data_Eq_eqArrayImpl any = func(f any) any {
	return func(xs any) any {
		return func(ys any) any {
			a, b := xs.([]any), ys.([]any)
			if len(a) != len(b) {
				return false
			}
			for i := range a {
				if !f.(func(any) any)(a[i]).(func(any) any)(b[i]).(bool) {
					return false
				}
			}
			return true
		}
	}
}

// ---------------------------------------------------------------------------
// Data.Ord  (returns the int -1/0/1 the PS Ordering decoder expects)
// ---------------------------------------------------------------------------

var Data_Ord_ordIntImpl any = _mkOrd(func(x, y any) int {
	a, b := x.(int), y.(int)
	if a < b {
		return -1
	}
	if a > b {
		return 1
	}
	return 0
})
var Data_Ord_ordNumberImpl any = _mkOrd(func(x, y any) int {
	a, b := x.(float64), y.(float64)
	// Mirror the reference structure exactly -- `x < y ? lt : x === y ? eq :
	// gt` -- rather than the equivalent-looking `<` / `>` / else. They part
	// company on NaN, which is neither less nor equal, so JS falls through to
	// GT where a `>` test falls through to EQ. `compare NaN 1.0` is GT.
	if a < b {
		return -1
	}
	if a == b {
		return 0
	}
	return 1
})
var Data_Ord_ordStringImpl any = _mkOrd(func(x, y any) int {
	a, b := x.(string), y.(string)
	if a < b {
		return -1
	}
	if a > b {
		return 1
	}
	return 0
})
var Data_Ord_ordCharImpl any = Data_Ord_ordStringImpl
var Data_Ord_ordBooleanImpl any = _mkOrd(func(x, y any) int {
	a, b := _b2i(x.(bool)), _b2i(y.(bool))
	if a < b {
		return -1
	}
	if a > b {
		return 1
	}
	return 0
})

var Data_Ord_ordArrayImpl any = func(f any) any {
	return func(xs any) any {
		return func(ys any) any {
			a, b := xs.([]any), ys.([]any)
			i := 0
			for i < len(a) && i < len(b) {
				o := f.(func(any) any)(a[i]).(func(any) any)(b[i]).(int)
				if o != 0 {
					return o
				}
				i++
			}
			switch {
			case len(a) == len(b):
				return 0
			case len(a) > len(b):
				return -1
			default:
				return 1
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Data.Bounded
// ---------------------------------------------------------------------------

var Data_Bounded_topInt any = 2147483647
var Data_Bounded_bottomInt any = -2147483648
var Data_Bounded_topChar any = string(rune(65535))
var Data_Bounded_bottomChar any = string(rune(0))
var Data_Bounded_topNumber any = math.Inf(1)
var Data_Bounded_bottomNumber any = math.Inf(-1)

// ---------------------------------------------------------------------------
// Data.Semigroup
// ---------------------------------------------------------------------------

var Data_Semigroup_concatString any = func(a any) any { return func(b any) any { return a.(string) + b.(string) } }
var Data_Semigroup_concatArray any = func(xs any) any {
	return func(ys any) any {
		a, b := xs.([]any), ys.([]any)
		if len(a) == 0 {
			return b
		}
		if len(b) == 0 {
			return a
		}
		out := make([]any, 0, len(a)+len(b))
		out = append(out, a...)
		out = append(out, b...)
		return out
	}
}

// ---------------------------------------------------------------------------
// Data.Functor / Control.Apply / Control.Bind / Control.Extend (arrays)
// ---------------------------------------------------------------------------

var Data_Functor_arrayMap any = func(f any) any {
	return func(arr any) any {
		a := arr.([]any)
		out := make([]any, len(a))
		g := f.(func(any) any)
		for i, x := range a {
			out[i] = g(x)
		}
		return out
	}
}

var Control_Apply_arrayApply any = func(fs any) any {
	return func(xs any) any {
		ff, xx := fs.([]any), xs.([]any)
		out := make([]any, 0, len(ff)*len(xx))
		for _, f := range ff {
			g := f.(func(any) any)
			for _, x := range xx {
				out = append(out, g(x))
			}
		}
		return out
	}
}

var Control_Bind_arrayBind any = func(arr any) any {
	return func(f any) any {
		a := arr.([]any)
		g := f.(func(any) any)
		out := []any{}
		for _, x := range a {
			out = append(out, g(x).([]any)...)
		}
		return out
	}
}

var Control_Extend_arrayExtend any = func(f any) any {
	return func(xs any) any {
		a := xs.([]any)
		g := f.(func(any) any)
		out := make([]any, len(a))
		for i := range a {
			out[i] = g(a[i:])
		}
		return out
	}
}

// ---------------------------------------------------------------------------
// Data.Show
// ---------------------------------------------------------------------------

var Data_Show_showIntImpl any = func(n any) any { return _showInt(n.(int)) }
var Data_Show_showNumberImpl any = func(n any) any { return _showNumber(n.(float64)) }
var Data_Show_showCharImpl any = func(c any) any { return _showChar(c.(string)) }
var Data_Show_showStringImpl any = func(s any) any { return _showString(s.(string)) }
var Data_Show_showArrayImpl any = func(f any) any {
	return func(xs any) any {
		a := xs.([]any)
		g := f.(func(any) any)
		parts := make([]string, len(a))
		for i, x := range a {
			parts[i] = g(x).(string)
		}
		return "[" + strings.Join(parts, ",") + "]"
	}
}

// ---------------------------------------------------------------------------
// Effect / Effect.Console
// ---------------------------------------------------------------------------

var Effect_pureE any = func(a any) any { return func() any { return a } }
var Effect_bindE any = func(a any) any {
	return func(f any) any {
		return func() any {
			return f.(func(any) any)(a.(func() any)()).(func() any)()
		}
	}
}

func _consoleThunk(s any, w *os.File) any {
	return func() any {
		fmt.Fprintln(w, s.(string))
		return nil
	}
}

var Effect_Console_log any = func(s any) any { return _consoleThunk(s, os.Stdout) }
var Effect_Console_info any = func(s any) any { return _consoleThunk(s, os.Stdout) }
var Effect_Console_debug any = func(s any) any { return _consoleThunk(s, os.Stdout) }
var Effect_Console_warn any = func(s any) any { return _consoleThunk(s, os.Stderr) }
var Effect_Console_error any = func(s any) any { return _consoleThunk(s, os.Stderr) }
var Effect_Console_group any = func(s any) any { return _consoleThunk(s, os.Stdout) }
var Effect_Console_groupEnd any = func() any { return nil }

// ---------------------------------------------------------------------------
// Data.Function.Uncurried  (FnN represented as Go variadic func(...any) any)
// ---------------------------------------------------------------------------

// _mkFn turns a curried fn into an n-ary uncurried variadic: applies fn one
// argument at a time over the variadic args. (mkFn0 is special: see below.)
func _mkFn(n int, fn any) any {
	return func(args ...any) any {
		r := fn
		for i := 0; i < n; i++ {
			r = r.(func(any) any)(args[i])
		}
		return r
	}
}

// _runFn curries the application of an n-ary uncurried variadic: collects n
// arguments through unary closures, then calls the variadic with all of them.
func _runFn(n int, fn any) any {
	var collect func(acc []any) any
	collect = func(acc []any) any {
		if len(acc) == n {
			return fn.(func(...any) any)(acc...)
		}
		return func(x any) any { return collect(append(append([]any{}, acc...), x)) }
	}
	return collect(nil)
}

// mkFn0 :: (Unit -> a) -> Fn0 a ; the Fn0 is a 0-arg variadic that applies fn
// to unit (nil). runFn0 :: Fn0 a -> a invokes it.
var Data_Function_Uncurried_mkFn0 any = func(fn any) any {
	return func(args ...any) any { return fn.(func(any) any)(nil) }
}
var Data_Function_Uncurried_runFn0 any = func(fn any) any { return fn.(func(...any) any)() }

var Data_Function_Uncurried_mkFn2 any = func(fn any) any { return _mkFn(2, fn) }
var Data_Function_Uncurried_mkFn3 any = func(fn any) any { return _mkFn(3, fn) }
var Data_Function_Uncurried_mkFn4 any = func(fn any) any { return _mkFn(4, fn) }
var Data_Function_Uncurried_mkFn5 any = func(fn any) any { return _mkFn(5, fn) }
var Data_Function_Uncurried_mkFn6 any = func(fn any) any { return _mkFn(6, fn) }
var Data_Function_Uncurried_mkFn7 any = func(fn any) any { return _mkFn(7, fn) }
var Data_Function_Uncurried_mkFn8 any = func(fn any) any { return _mkFn(8, fn) }
var Data_Function_Uncurried_mkFn9 any = func(fn any) any { return _mkFn(9, fn) }
var Data_Function_Uncurried_mkFn10 any = func(fn any) any { return _mkFn(10, fn) }

var Data_Function_Uncurried_runFn2 any = func(fn any) any { return _runFn(2, fn) }
var Data_Function_Uncurried_runFn3 any = func(fn any) any { return _runFn(3, fn) }
var Data_Function_Uncurried_runFn4 any = func(fn any) any { return _runFn(4, fn) }
var Data_Function_Uncurried_runFn5 any = func(fn any) any { return _runFn(5, fn) }
var Data_Function_Uncurried_runFn6 any = func(fn any) any { return _runFn(6, fn) }
var Data_Function_Uncurried_runFn7 any = func(fn any) any { return _runFn(7, fn) }
var Data_Function_Uncurried_runFn8 any = func(fn any) any { return _runFn(8, fn) }
var Data_Function_Uncurried_runFn9 any = func(fn any) any { return _runFn(9, fn) }
var Data_Function_Uncurried_runFn10 any = func(fn any) any { return _runFn(10, fn) }

// ---------------------------------------------------------------------------
// Data.Enum (foreign: char <-> code point)
// ---------------------------------------------------------------------------

// Char is a single-char string; toCharCode/fromCharCode use codepoints (Go is
// UTF-8) -- the ASTRAL ledger. JS uses UTF-16 code units; for BMP chars these
// agree.
var Data_Enum_toCharCode any = func(c any) any { return int([]rune(c.(string))[0]) }
var Data_Enum_fromCharCode any = func(i any) any { return string(rune(i.(int))) }

// ---------------------------------------------------------------------------
// Data.Foldable (array folds)
// ---------------------------------------------------------------------------

var Data_Foldable_foldrArray any = func(f any) any {
	return func(init any) any {
		return func(xs any) any {
			arr := xs.([]any)
			acc := init
			for i := len(arr) - 1; i >= 0; i-- {
				acc = f.(func(any) any)(arr[i]).(func(any) any)(acc)
			}
			return acc
		}
	}
}
var Data_Foldable_foldlArray any = func(f any) any {
	return func(init any) any {
		return func(xs any) any {
			arr := xs.([]any)
			acc := init
			for i := 0; i < len(arr); i++ {
				acc = f.(func(any) any)(acc).(func(any) any)(arr[i])
			}
			return acc
		}
	}
}

// ---------------------------------------------------------------------------
// Data.FunctorWithIndex (indexed array map)
// ---------------------------------------------------------------------------

var Data_FunctorWithIndex_mapWithIndexArray any = func(f any) any {
	return func(xs any) any {
		arr := xs.([]any)
		result := make([]any, len(arr))
		for i := 0; i < len(arr); i++ {
			result[i] = f.(func(any) any)(i).(func(any) any)(arr[i])
		}
		return result
	}
}

// ---------------------------------------------------------------------------
// Data.Int.Bits (JS int32 bitwise semantics: result is ToInt32, except >>> is
// ToUint32; shift counts are masked to 5 bits. Faithful to JS, NOT a ledger
// divergence -- the int32 wrap is the whole point of these ops.)
// ---------------------------------------------------------------------------

var Data_Int_Bits_and any = func(n1 any) any {
	return func(n2 any) any { return _toInt32(n1.(int) & n2.(int)) }
}
var Data_Int_Bits_or any = func(n1 any) any {
	return func(n2 any) any { return _toInt32(n1.(int) | n2.(int)) }
}
var Data_Int_Bits_xor any = func(n1 any) any {
	return func(n2 any) any { return _toInt32(n1.(int) ^ n2.(int)) }
}
var Data_Int_Bits_shl any = func(n1 any) any {
	return func(n2 any) any { return int(int32(uint32(n1.(int)) << uint(n2.(int)&31))) }
}
var Data_Int_Bits_shr any = func(n1 any) any {
	return func(n2 any) any { return int(int32(uint32(n1.(int))) >> uint(n2.(int)&31)) }
}
var Data_Int_Bits_zshr any = func(n1 any) any {
	return func(n2 any) any { return int(uint32(n1.(int)) >> uint(n2.(int)&31)) }
}
var Data_Int_Bits_complement any = func(n any) any { return _toInt32(^n.(int)) }

// ---------------------------------------------------------------------------
// Data.Int
// ---------------------------------------------------------------------------

// fromNumberImpl(just)(nothing)(n): Just n when n is an int32-valued Number.
var Data_Int_fromNumberImpl any = func(just any) any {
	return func(nothing any) any {
		return func(n any) any {
			f := n.(float64)
			i := int32(f)
			if float64(i) == f {
				return just.(func(any) any)(int(i))
			}
			return nothing
		}
	}
}
var Data_Int_toNumber any = func(n any) any { return float64(n.(int)) }

// quot/rem: truncating division (toward zero); Go int division already
// truncates toward zero. pow: Math.pow then ToInt32 (the `| 0`). toStringAs:
// radix conversion (lowercase digits, like JS Number.prototype.toString).
// Both guard zero, which Go does not: `x / 0` panics where JS's `x / 0 | 0`
// is 0. The reference for `quot` is exactly that -- Infinity coerced through
// ToInt32 -- so 0 is the right answer and not merely a safe one. `rem` is
// different: JS `x % 0` is NaN, which is not an Int at all, so no non-JS
// backend can reproduce it and all three return 0. That is a ledger entry
// (int-rem-zero), not a bug. Found by Test.Boundaries; before it, both
// panicked.
var Data_Int_quot any = func(x any) any {
	return func(y any) any {
		if y.(int) == 0 {
			return 0
		}
		return x.(int) / y.(int)
	}
}
var Data_Int_rem any = func(x any) any {
	return func(y any) any {
		if y.(int) == 0 {
			return 0
		}
		return x.(int) % y.(int)
	}
}
var Data_Int_pow any = func(x any) any {
	return func(y any) any {
		return _toInt32(int(int64(math.Pow(float64(x.(int)), float64(y.(int))))))
	}
}
var Data_Int_toStringAs any = func(radix any) any {
	return func(i any) any { return strconv.FormatInt(int64(i.(int)), radix.(int)) }
}

// fromStringAsImpl(just)(nothing)(radix)(s): parse with radix, Just iff the
// whole string is valid digits (+/- allowed) AND fits int32. Called curried.
var Data_Int_fromStringAsImpl any = func(just any) any {
	return func(nothing any) any {
		return func(radix any) any {
			r := radix.(int)
			return func(s any) any {
				i64, err := strconv.ParseInt(s.(string), r, 64)
				if err != nil {
					return nothing
				}
				i := int32(i64)
				if int64(i) == i64 {
					return just.(func(any) any)(int(i))
				}
				return nothing
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Data.Number
// ---------------------------------------------------------------------------

var Data_Number_ceil any = func(n any) any { return math.Ceil(n.(float64)) }
var Data_Number_floor any = func(n any) any { return math.Floor(n.(float64)) }

// JS Math.round rounds half toward +Infinity (= floor(x+0.5)); Go math.Round
// rounds half away from zero. Mirror JS.
// Data_Number_round is NOT math.Floor(n+0.5): that is the classic Math.round
// polyfill bug. Wherever n+0.5 rounds UP in float64 the result is one too high
// -- round(0.49999999999999994) gave 1 where JS gives 0, and
// round(4503599627370497) gave ...98 where JS returns its argument. Compare the
// fraction against 1/2 instead; nothing is added to n.
var Data_Number_round any = func(n any) any {
	f := n.(float64)
	if math.IsInf(f, 0) || math.IsNaN(f) {
		return f
	}
	fl := math.Floor(f)
	r := fl
	if f-fl >= 0.5 {
		r = fl + 1
	}
	// JS Math.round(-0.2) is -0, and the sign of zero is observable via 1.0/x.
	if r == 0 && math.Signbit(f) {
		return math.Copysign(0, -1)
	}
	return r
}
var Data_Number_trunc any = func(n any) any { return math.Trunc(n.(float64)) }
var Data_Number_isFinite any = func(n any) any {
	f := n.(float64)
	return !math.IsInf(f, 0) && !math.IsNaN(f)
}

// fromStringImpl(str, isFinite, just, nothing): uncurried (called via runFn4).
// `Data.Number.fromString` is `parseFloat` behind an isFinite guard, and
// parseFloat is a PREFIX parser: it skips leading whitespace, takes the
// longest numeric prefix and ignores the rest. So "1.5x" is 1.5, "0x10" is 0
// (it stops at the `x`), " 1.5 " is 1.5 and "1_000" is 1 -- where Go's
// strconv accepts the underscore and answers 1000. Found by Test.Boundaries.
var _floatPrefix = regexp.MustCompile(
	`^[\s]*[+-]?(?:Infinity|(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[eE][+-]?[0-9]+)?)`)

func _parseFloat(s string) float64 {
	m := _floatPrefix.FindString(s)
	if m == "" {
		return math.NaN()
	}
	t := strings.TrimSpace(m)
	if strings.HasSuffix(t, "Infinity") {
		if strings.HasPrefix(t, "-") {
			return math.Inf(-1)
		}
		return math.Inf(1)
	}
	f, err := strconv.ParseFloat(t, 64)
	if err != nil {
		return math.NaN()
	}
	return f
}

var Data_Number_fromStringImpl any = func(args ...any) any {
	num := _parseFloat(args[0].(string))
	isFinite := args[1].(func(any) any)
	just := args[2].(func(any) any)
	nothing := args[3]
	// No error path: _parseFloat answers NaN where parseFloat does, and the
	// isFinite guard is what turns that into Nothing -- exactly as the JS
	// foreign does.
	if isFinite(num).(bool) {
		return just(num)
	}
	return nothing
}

// constants + Math.* functions (curried where binary).
var Data_Number_nan any = math.NaN()
var Data_Number_infinity any = math.Inf(1)
var Data_Number_isNaN any = func(n any) any { return math.IsNaN(n.(float64)) }
var Data_Number_abs any = func(n any) any { return math.Abs(n.(float64)) }
var Data_Number_acos any = func(n any) any { return math.Acos(n.(float64)) }
var Data_Number_asin any = func(n any) any { return math.Asin(n.(float64)) }
var Data_Number_atan any = func(n any) any { return math.Atan(n.(float64)) }
var Data_Number_cos any = func(n any) any { return math.Cos(n.(float64)) }
var Data_Number_exp any = func(n any) any { return math.Exp(n.(float64)) }
var Data_Number_log any = func(n any) any { return math.Log(n.(float64)) }
var Data_Number_sin any = func(n any) any { return math.Sin(n.(float64)) }
var Data_Number_sqrt any = func(n any) any { return math.Sqrt(n.(float64)) }
var Data_Number_tan any = func(n any) any { return math.Tan(n.(float64)) }
var Data_Number_atan2 any = func(y any) any {
	return func(x any) any { return math.Atan2(y.(float64), x.(float64)) }
}

// ECMAScript Math.pow is NOT IEEE pow, and the order of its rules matters:
// an exponent of zero wins over a NaN base, but a NaN exponent beats
// everything else, and |base| == 1 with an infinite exponent is NaN where
// IEEE says 1. Go's math.Pow follows IEEE, so the two special cases have to
// be layered on top. Found by Test.Boundaries.
var Data_Number_pow any = func(n any) any {
	return func(p any) any {
		b, e := n.(float64), p.(float64)
		if e == 0 {
			return 1.0
		}
		if math.IsNaN(e) {
			return math.NaN()
		}
		if math.Abs(b) == 1 && math.IsInf(e, 0) {
			return math.NaN()
		}
		return math.Pow(b, e)
	}
}
var Data_Number_remainder any = func(n any) any {
	return func(m any) any { return math.Mod(n.(float64), m.(float64)) }
}
var Data_Number_max any = func(a any) any {
	return func(b any) any { return math.Max(a.(float64), b.(float64)) }
}
var Data_Number_min any = func(a any) any {
	return func(b any) any { return math.Min(a.(float64), b.(float64)) }
}

// JS Math.sign: returns x unchanged for 0/-0/NaN, else +/-1.
var Data_Number_sign any = func(x any) any {
	f := x.(float64)
	if f == 0 || math.IsNaN(f) {
		return f
	}
	if f < 0 {
		return -1.0
	}
	return 1.0
}

// ---------------------------------------------------------------------------
// Data.Traversable (divide-and-conquer applicative traverse over an array)
// traverseArrayImpl(apply)(map)(pure)(f)(array) -- curried.
// ---------------------------------------------------------------------------

var Data_Traversable_traverseArrayImpl any = func(apply any) any {
	return func(mapf any) any {
		return func(pure any) any {
			return func(f any) any {
				return func(array any) any {
					arr := array.([]any)
					ap := apply.(func(any) any)
					mp := mapf.(func(any) any)
					pr := pure.(func(any) any)
					ff := f.(func(any) any)
					array1 := func(a any) any { return []any{a} }
					array2 := func(a any) any { return func(b any) any { return []any{a, b} } }
					array3 := func(a any) any {
						return func(b any) any { return func(c any) any { return []any{a, b, c} } }
					}
					concat2 := func(xs any) any {
						return func(ys any) any {
							return append(append([]any{}, xs.([]any)...), ys.([]any)...)
						}
					}
					var goRec func(bot, top int) any
					goRec = func(bot, top int) any {
						switch top - bot {
						case 0:
							return pr([]any{})
						case 1:
							return mp(array1).(func(any) any)(ff(arr[bot]))
						case 2:
							return ap(mp(array2).(func(any) any)(ff(arr[bot]))).(func(any) any)(ff(arr[bot+1]))
						case 3:
							return ap(ap(mp(array3).(func(any) any)(ff(arr[bot]))).(func(any) any)(ff(arr[bot+1]))).(func(any) any)(ff(arr[bot+2]))
						default:
							pivot := bot + ((top-bot)/4)*2
							return ap(mp(concat2).(func(any) any)(goRec(bot, pivot))).(func(any) any)(goRec(pivot, top))
						}
					}
					return goRec(0, len(arr))
				}
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Data.Unfoldable / Data.Unfoldable1 (array unfolds)
// ---------------------------------------------------------------------------

var Data_Unfoldable_unfoldrArrayImpl any = func(isNothing any) any {
	return func(fromJust any) any {
		return func(fst any) any {
			return func(snd any) any {
				return func(f any) any {
					return func(b any) any {
						isN := isNothing.(func(any) any)
						fj := fromJust.(func(any) any)
						ft := fst.(func(any) any)
						sd := snd.(func(any) any)
						ff := f.(func(any) any)
						result := []any{}
						value := b
						for {
							maybe := ff(value)
							if isN(maybe).(bool) {
								return result
							}
							tuple := fj(maybe)
							result = append(result, ft(tuple))
							value = sd(tuple)
						}
					}
				}
			}
		}
	}
}
var Data_Unfoldable1_unfoldr1ArrayImpl any = func(isNothing any) any {
	return func(fromJust any) any {
		return func(fst any) any {
			return func(snd any) any {
				return func(f any) any {
					return func(b any) any {
						isN := isNothing.(func(any) any)
						fj := fromJust.(func(any) any)
						ft := fst.(func(any) any)
						sd := snd.(func(any) any)
						ff := f.(func(any) any)
						result := []any{}
						value := b
						for {
							tuple := ff(value)
							result = append(result, ft(tuple))
							maybe := sd(tuple)
							if isN(maybe).(bool) {
								return result
							}
							value = fj(maybe)
						}
					}
				}
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Effect.Ref (mutable cell = map[string]any{"value": ...}; ops are Effect thunks)
// ---------------------------------------------------------------------------

var Effect_Ref__new any = func(val any) any {
	return func() any { return map[string]any{"value": val} }
}
var Effect_Ref_read any = func(ref any) any {
	return func() any { return ref.(map[string]any)["value"] }
}
var Effect_Ref_write any = func(val any) any {
	return func(ref any) any {
		return func() any {
			ref.(map[string]any)["value"] = val
			return nil
		}
	}
}
var Effect_Ref_modifyImpl any = func(f any) any {
	return func(ref any) any {
		return func() any {
			r := ref.(map[string]any)
			t := f.(func(any) any)(r["value"]).(map[string]any)
			r["value"] = t["state"]
			return t["value"]
		}
	}
}

// ---------------------------------------------------------------------------
// Effect (control-flow primitives; the loop body is an Effect thunk)
// ---------------------------------------------------------------------------

var Effect_untilE any = func(f any) any {
	return func() any {
		for !f.(func() any)().(bool) {
		}
		return nil
	}
}
var Effect_whileE any = func(f any) any {
	return func(a any) any {
		return func() any {
			for f.(func() any)().(bool) {
				a.(func() any)()
			}
			return nil
		}
	}
}
var Effect_forE any = func(lo any) any {
	return func(hi any) any {
		return func(f any) any {
			return func() any {
				for i := lo.(int); i < hi.(int); i++ {
					f.(func(any) any)(i).(func() any)()
				}
				return nil
			}
		}
	}
}
var Effect_foreachE any = func(as any) any {
	return func(f any) any {
		return func() any {
			for _, x := range as.([]any) {
				f.(func(any) any)(x).(func() any)()
			}
			return nil
		}
	}
}

// ---------------------------------------------------------------------------
// Effect.Uncurried (EffectFnN = uncurried `func(...any) any`; mkEffectFnN
// applies a curried Effect-returning fn to all args and RUNS the effect;
// runEffectFnN curries N args then defers in an Effect thunk -- same shape as
// _runSTFn) + Effect.Unsafe.
// ---------------------------------------------------------------------------

func _mkEffectFn(n int, fn any) any {
	return func(args ...any) any {
		r := fn
		for i := 0; i < n; i++ {
			r = r.(func(any) any)(args[i])
		}
		return r.(func() any)()
	}
}

var Effect_Uncurried_mkEffectFn1 any = func(fn any) any { return _mkEffectFn(1, fn) }
var Effect_Uncurried_mkEffectFn2 any = func(fn any) any { return _mkEffectFn(2, fn) }
var Effect_Uncurried_mkEffectFn3 any = func(fn any) any { return _mkEffectFn(3, fn) }
var Effect_Uncurried_mkEffectFn4 any = func(fn any) any { return _mkEffectFn(4, fn) }
var Effect_Uncurried_mkEffectFn5 any = func(fn any) any { return _mkEffectFn(5, fn) }
var Effect_Uncurried_mkEffectFn6 any = func(fn any) any { return _mkEffectFn(6, fn) }
var Effect_Uncurried_mkEffectFn7 any = func(fn any) any { return _mkEffectFn(7, fn) }
var Effect_Uncurried_mkEffectFn8 any = func(fn any) any { return _mkEffectFn(8, fn) }
var Effect_Uncurried_mkEffectFn9 any = func(fn any) any { return _mkEffectFn(9, fn) }
var Effect_Uncurried_mkEffectFn10 any = func(fn any) any { return _mkEffectFn(10, fn) }

var Effect_Uncurried_runEffectFn1 any = func(fn any) any { return _runSTFn(1, fn) }
var Effect_Uncurried_runEffectFn2 any = func(fn any) any { return _runSTFn(2, fn) }
var Effect_Uncurried_runEffectFn3 any = func(fn any) any { return _runSTFn(3, fn) }
var Effect_Uncurried_runEffectFn4 any = func(fn any) any { return _runSTFn(4, fn) }
var Effect_Uncurried_runEffectFn5 any = func(fn any) any { return _runSTFn(5, fn) }
var Effect_Uncurried_runEffectFn6 any = func(fn any) any { return _runSTFn(6, fn) }
var Effect_Uncurried_runEffectFn7 any = func(fn any) any { return _runSTFn(7, fn) }
var Effect_Uncurried_runEffectFn8 any = func(fn any) any { return _runSTFn(8, fn) }
var Effect_Uncurried_runEffectFn9 any = func(fn any) any { return _runSTFn(9, fn) }
var Effect_Uncurried_runEffectFn10 any = func(fn any) any { return _runSTFn(10, fn) }

var Effect_Unsafe_unsafePerformEffect any = func(f any) any { return f.(func() any)() }

// ---------------------------------------------------------------------------
// Control.Monad.ST.Internal (STRef = map[string]any{"value": ...}, same as
// Effect.Ref; ST actions are `func() any` thunks, same as Effect)
// ---------------------------------------------------------------------------

var Control_Monad_ST_Internal_pure_ any = func(a any) any { return func() any { return a } }
var Control_Monad_ST_Internal_bind_ any = func(a any) any {
	return func(f any) any {
		return func() any {
			return f.(func(any) any)(a.(func() any)()).(func() any)()
		}
	}
}

// foreign map_ (mangles to map__: core "map" is Go-reserved, plus the PS prime _).
var Control_Monad_ST_Internal_map__ any = func(f any) any {
	return func(a any) any {
		return func() any { return f.(func(any) any)(a.(func() any)()) }
	}
}
var Control_Monad_ST_Internal_run any = func(f any) any { return f.(func() any)() }
var Control_Monad_ST_Internal_while any = func(f any) any {
	return func(a any) any {
		return func() any {
			for f.(func() any)().(bool) {
				a.(func() any)()
			}
			return nil
		}
	}
}
var Control_Monad_ST_Internal_for_ any = func(lo any) any {
	return func(hi any) any {
		return func(f any) any {
			return func() any {
				for i := lo.(int); i < hi.(int); i++ {
					f.(func(any) any)(i).(func() any)()
				}
				return nil
			}
		}
	}
}
var Control_Monad_ST_Internal_foreach any = func(as any) any {
	return func(f any) any {
		return func() any {
			for _, x := range as.([]any) {
				f.(func(any) any)(x).(func() any)()
			}
			return nil
		}
	}
}
var Control_Monad_ST_Internal_new_ any = func(val any) any {
	return func() any { return map[string]any{"value": val} }
}
var Control_Monad_ST_Internal_read any = func(ref any) any {
	return func() any { return ref.(map[string]any)["value"] }
}
var Control_Monad_ST_Internal_modifyImpl any = func(f any) any {
	return func(ref any) any {
		return func() any {
			r := ref.(map[string]any)
			t := f.(func(any) any)(r["value"]).(map[string]any)
			r["value"] = t["state"]
			return t["value"]
		}
	}
}

// NB: ST write returns the written value (JS `ref.value = a` evaluates to a),
// unlike Effect.Ref.write which returns unit.
var Control_Monad_ST_Internal_write any = func(a any) any {
	return func(ref any) any {
		return func() any {
			ref.(map[string]any)["value"] = a
			return a
		}
	}
}

// ---------------------------------------------------------------------------
// Control.Monad.ST.Uncurried (runSTFnN: like _runFn but the final application
// is wrapped in an ST thunk)
// ---------------------------------------------------------------------------

func _runSTFn(n int, fn any) any {
	var collect func(acc []any) any
	collect = func(acc []any) any {
		if len(acc) == n {
			return func() any { return fn.(func(...any) any)(acc...) }
		}
		return func(x any) any { return collect(append(append([]any{}, acc...), x)) }
	}
	return collect(nil)
}

var Control_Monad_ST_Uncurried_runSTFn1 any = func(fn any) any { return _runSTFn(1, fn) }
var Control_Monad_ST_Uncurried_runSTFn2 any = func(fn any) any { return _runSTFn(2, fn) }
var Control_Monad_ST_Uncurried_runSTFn3 any = func(fn any) any { return _runSTFn(3, fn) }
var Control_Monad_ST_Uncurried_runSTFn4 any = func(fn any) any { return _runSTFn(4, fn) }

// ---------------------------------------------------------------------------
// Data.Array.ST (mutable arrays = *[]any for reference semantics; primitives
// are uncurried, called via runSTFnN. freeze/thaw/clone copy; unsafe variants
// alias. new_ is itself the ST thunk producing a fresh array.)
// ---------------------------------------------------------------------------

var Data_Array_ST_new_ any = func() any { s := make([]any, 0); return &s }
var Data_Array_ST_lengthImpl any = func(args ...any) any { return len(*(args[0].(*[]any))) }
var Data_Array_ST_peekImpl any = func(args ...any) any {
	just := args[0].(func(any) any)
	nothing := args[1]
	i := args[2].(int)
	xs := *(args[3].(*[]any))
	if i >= 0 && i < len(xs) {
		return just(xs[i])
	}
	return nothing
}
var Data_Array_ST_pokeImpl any = func(args ...any) any {
	i := args[0].(int)
	a := args[1]
	p := args[2].(*[]any)
	ok := i >= 0 && i < len(*p)
	if ok {
		(*p)[i] = a
	}
	return ok
}
var Data_Array_ST_pushImpl any = func(args ...any) any {
	p := args[1].(*[]any)
	*p = append(*p, args[0])
	return len(*p)
}
var Data_Array_ST_pushAllImpl any = func(args ...any) any {
	p := args[1].(*[]any)
	*p = append(*p, args[0].([]any)...)
	return len(*p)
}
var Data_Array_ST_popImpl any = func(args ...any) any {
	just := args[0].(func(any) any)
	nothing := args[1]
	p := args[2].(*[]any)
	if n := len(*p); n > 0 {
		v := (*p)[n-1]
		*p = (*p)[:n-1]
		return just(v)
	}
	return nothing
}
var Data_Array_ST_shiftImpl any = func(args ...any) any {
	just := args[0].(func(any) any)
	nothing := args[1]
	p := args[2].(*[]any)
	if len(*p) > 0 {
		v := (*p)[0]
		*p = (*p)[1:]
		return just(v)
	}
	return nothing
}
var Data_Array_ST_unshiftAllImpl any = func(args ...any) any {
	as := args[0].([]any)
	p := args[1].(*[]any)
	*p = append(append([]any{}, as...), (*p)...)
	return len(*p)
}
var Data_Array_ST_spliceImpl any = func(args ...any) any {
	i := args[0].(int)
	howMany := args[1].(int)
	bs := args[2].([]any)
	p := args[3].(*[]any)
	arr := *p
	if i > len(arr) {
		i = len(arr)
	}
	end := i + howMany
	if end > len(arr) {
		end = len(arr)
	}
	removed := append([]any{}, arr[i:end]...)
	out := append([]any{}, arr[:i]...)
	out = append(out, bs...)
	out = append(out, arr[end:]...)
	*p = out
	return removed
}
var Data_Array_ST_unsafeFreezeImpl any = func(args ...any) any { return *(args[0].(*[]any)) }
var Data_Array_ST_unsafeThawImpl any = func(args ...any) any {
	s := args[0].([]any)
	return &s
}
var Data_Array_ST_freezeImpl any = func(args ...any) any {
	return append([]any{}, (*(args[0].(*[]any)))...)
}
var Data_Array_ST_thawImpl any = func(args ...any) any {
	s := append([]any{}, args[0].([]any)...)
	return &s
}
var Data_Array_ST_cloneImpl any = func(args ...any) any {
	s := append([]any{}, (*(args[0].(*[]any)))...)
	return &s
}
var Data_Array_ST_toAssocArrayImpl any = func(args ...any) any {
	src := *(args[0].(*[]any))
	out := make([]any, len(src))
	for i, v := range src {
		out[i] = map[string]any{"value": v, "index": i}
	}
	return out
}

// In-place stable merge sort (mirrors the JS mergeFromTo). compare returns an
// Ordering ADT; fromOrdering maps it to an int (-1/0/1). Returns the STArray.
var Data_Array_ST_sortByImpl any = func(args ...any) any {
	compare := args[0].(func(any) any)
	fromOrdering := args[1].(func(any) any)
	p := args[2].(*[]any)
	xs := *p
	if len(xs) < 2 {
		return p
	}
	var mergeFromTo func(xs1, xs2 []any, from, to int)
	mergeFromTo = func(xs1, xs2 []any, from, to int) {
		mid := from + ((to - from) >> 1)
		if mid-from > 1 {
			mergeFromTo(xs2, xs1, from, mid)
		}
		if to-mid > 1 {
			mergeFromTo(xs2, xs1, mid, to)
		}
		i, j, k := from, mid, from
		for i < mid && j < to {
			x, y := xs2[i], xs2[j]
			c := fromOrdering(compare(x).(func(any) any)(y)).(int)
			if c > 0 {
				xs1[k] = y
				k++
				j++
			} else {
				xs1[k] = x
				k++
				i++
			}
		}
		for i < mid {
			xs1[k] = xs2[i]
			k++
			i++
		}
		for j < to {
			xs1[k] = xs2[j]
			k++
			j++
		}
	}
	mergeFromTo(xs, append([]any{}, xs...), 0, len(xs))
	return p
}

// ---------------------------------------------------------------------------
// Data.Array (immutable []any; multi-arg primitives are uncurried/variadic via
// runFnN; length/reverse/concat are curried single-arg)
// ---------------------------------------------------------------------------

var Data_Array_length any = func(xs any) any { return len(xs.([]any)) }
var Data_Array_reverse any = func(l any) any {
	src := l.([]any)
	n := len(src)
	out := make([]any, n)
	for i, x := range src {
		out[n-1-i] = x
	}
	return out
}
var Data_Array_concat any = func(xss any) any {
	out := []any{}
	for _, xs := range xss.([]any) {
		out = append(out, xs.([]any)...)
	}
	return out
}
var Data_Array_rangeImpl any = func(args ...any) any {
	start, end := args[0].(int), args[1].(int)
	step := 1
	if start > end {
		step = -1
	}
	result := make([]any, step*(end-start)+1)
	i, n := start, 0
	for i != end {
		result[n] = i
		n++
		i += step
	}
	result[n] = i
	return result
}
var Data_Array_replicateImpl any = func(args ...any) any {
	count := args[0].(int)
	value := args[1]
	if count < 1 {
		return []any{}
	}
	result := make([]any, count)
	for i := range result {
		result[i] = value
	}
	return result
}
var Data_Array_fromFoldableImpl any = func(args ...any) any {
	foldr := args[0].(func(any) any)
	xs := args[1]
	curryCons := func(head any) any {
		return func(tail any) any { return map[string]any{"head": head, "tail": tail} }
	}
	list := foldr(curryCons).(func(any) any)(_flEmpty).(func(any) any)(xs)
	result := []any{}
	for list != _flEmpty {
		node := list.(map[string]any)
		result = append(result, node["head"])
		list = node["tail"]
	}
	return result
}
var Data_Array_unconsImpl any = func(args ...any) any {
	empty := args[0].(func(any) any)
	next := args[1].(func(any) any)
	xs := args[2].([]any)
	if len(xs) == 0 {
		return empty(map[string]any{})
	}
	return next(xs[0]).(func(any) any)(append([]any{}, xs[1:]...))
}
var Data_Array_indexImpl any = func(args ...any) any {
	just := args[0].(func(any) any)
	nothing := args[1]
	xs := args[2].([]any)
	i := args[3].(int)
	if i < 0 || i >= len(xs) {
		return nothing
	}
	return just(xs[i])
}
var Data_Array_findMapImpl any = func(args ...any) any {
	nothing := args[0]
	isJust := args[1].(func(any) any)
	f := args[2].(func(any) any)
	xs := args[3].([]any)
	for _, x := range xs {
		r := f(x)
		if isJust(r).(bool) {
			return r
		}
	}
	return nothing
}
var Data_Array_findIndexImpl any = func(args ...any) any {
	just := args[0].(func(any) any)
	nothing := args[1]
	f := args[2].(func(any) any)
	xs := args[3].([]any)
	for i, x := range xs {
		if f(x).(bool) {
			return just(i)
		}
	}
	return nothing
}
var Data_Array_findLastIndexImpl any = func(args ...any) any {
	just := args[0].(func(any) any)
	nothing := args[1]
	f := args[2].(func(any) any)
	xs := args[3].([]any)
	for i := len(xs) - 1; i >= 0; i-- {
		if f(xs[i]).(bool) {
			return just(i)
		}
	}
	return nothing
}
var Data_Array__insertAt any = func(args ...any) any {
	just := args[0].(func(any) any)
	nothing := args[1]
	i := args[2].(int)
	a := args[3]
	l := args[4].([]any)
	if i < 0 || i > len(l) {
		return nothing
	}
	out := make([]any, 0, len(l)+1)
	out = append(out, l[:i]...)
	out = append(out, a)
	out = append(out, l[i:]...)
	return just(out)
}
var Data_Array__deleteAt any = func(args ...any) any {
	just := args[0].(func(any) any)
	nothing := args[1]
	i := args[2].(int)
	l := args[3].([]any)
	if i < 0 || i >= len(l) {
		return nothing
	}
	out := append([]any{}, l[:i]...)
	out = append(out, l[i+1:]...)
	return just(out)
}
var Data_Array__updateAt any = func(args ...any) any {
	just := args[0].(func(any) any)
	nothing := args[1]
	i := args[2].(int)
	a := args[3]
	l := args[4].([]any)
	if i < 0 || i >= len(l) {
		return nothing
	}
	out := append([]any{}, l...)
	out[i] = a
	return just(out)
}
var Data_Array_filterImpl any = func(args ...any) any {
	f := args[0].(func(any) any)
	xs := args[1].([]any)
	out := []any{}
	for _, x := range xs {
		if f(x).(bool) {
			out = append(out, x)
		}
	}
	return out
}
var Data_Array_partitionImpl any = func(args ...any) any {
	f := args[0].(func(any) any)
	xs := args[1].([]any)
	yes, no := []any{}, []any{}
	for _, x := range xs {
		if f(x).(bool) {
			yes = append(yes, x)
		} else {
			no = append(no, x)
		}
	}
	return map[string]any{"yes": yes, "no": no}
}
var Data_Array_scanlImpl any = func(args ...any) any {
	f := args[0].(func(any) any)
	acc := args[1]
	xs := args[2].([]any)
	out := make([]any, len(xs))
	for i, x := range xs {
		acc = f(acc).(func(any) any)(x)
		out[i] = acc
	}
	return out
}
var Data_Array_scanrImpl any = func(args ...any) any {
	f := args[0].(func(any) any)
	acc := args[1]
	xs := args[2].([]any)
	out := make([]any, len(xs))
	for i := len(xs) - 1; i >= 0; i-- {
		acc = f(xs[i]).(func(any) any)(acc)
		out[i] = acc
	}
	return out
}
var Data_Array_sortByImpl any = func(args ...any) any {
	compare := args[0].(func(any) any)
	fromOrdering := args[1].(func(any) any)
	xs := args[2].([]any)
	if len(xs) < 2 {
		return xs
	}
	out := append([]any{}, xs...)
	_mergeFromTo(compare, fromOrdering, out, append([]any{}, xs...), 0, len(xs))
	return out
}
var Data_Array_sliceImpl any = func(args ...any) any {
	s, e := args[0].(int), args[1].(int)
	l := args[2].([]any)
	n := len(l)
	if s < 0 {
		if s += n; s < 0 {
			s = 0
		}
	} else if s > n {
		s = n
	}
	if e < 0 {
		if e += n; e < 0 {
			e = 0
		}
	} else if e > n {
		e = n
	}
	if s > e {
		s = e
	}
	return append([]any{}, l[s:e]...)
}
var Data_Array_zipWithImpl any = func(args ...any) any {
	f := args[0].(func(any) any)
	xs := args[1].([]any)
	ys := args[2].([]any)
	l := len(xs)
	if len(ys) < l {
		l = len(ys)
	}
	out := make([]any, l)
	for i := 0; i < l; i++ {
		out[i] = f(xs[i]).(func(any) any)(ys[i])
	}
	return out
}
var Data_Array_anyImpl any = func(args ...any) any {
	p := args[0].(func(any) any)
	xs := args[1].([]any)
	for _, x := range xs {
		if p(x).(bool) {
			return true
		}
	}
	return false
}
var Data_Array_allImpl any = func(args ...any) any {
	p := args[0].(func(any) any)
	xs := args[1].([]any)
	for _, x := range xs {
		if !p(x).(bool) {
			return false
		}
	}
	return true
}
var Data_Array_unsafeIndexImpl any = func(args ...any) any {
	return args[0].([]any)[args[1].(int)]
}

// ---------------------------------------------------------------------------
// Data.Array.NonEmpty.Internal
// ---------------------------------------------------------------------------

var Data_Array_NonEmpty_Internal_foldr1Impl any = func(args ...any) any {
	f := args[0].(func(any) any)
	xs := args[1].([]any)
	acc := xs[len(xs)-1]
	for i := len(xs) - 2; i >= 0; i-- {
		acc = f(xs[i]).(func(any) any)(acc)
	}
	return acc
}
var Data_Array_NonEmpty_Internal_foldl1Impl any = func(args ...any) any {
	f := args[0].(func(any) any)
	xs := args[1].([]any)
	acc := xs[0]
	for i := 1; i < len(xs); i++ {
		acc = f(acc).(func(any) any)(xs[i])
	}
	return acc
}

// traverse1Impl(apply, map, f) -> array -> result. Uses a Cont trampoline (per
// the JS) to fold right without deep recursion, building a cons-list inside the
// applicative then converting to an array.
var Data_Array_NonEmpty_Internal_traverse1Impl any = func(args ...any) any {
	apply := args[0].(func(any) any)
	mapf := args[1].(func(any) any)
	f := args[2].(func(any) any)
	type cell struct{ head, tail any }
	var emptyL any = &cell{}
	consList := func(x any) any {
		return func(xs any) any { return &cell{head: x, tail: xs} }
	}
	finalCell := func(head any) any { return &cell{head: head, tail: emptyL} }
	listToArray := func(list any) any {
		arr := []any{}
		for xs := list; xs != emptyL; {
			c := xs.(*cell)
			arr = append(arr, c.head)
			xs = c.tail
		}
		return arr
	}
	buildFrom := func(x, ys any) any {
		return apply(mapf(consList).(func(any) any)(f(x))).(func(any) any)(ys)
	}
	type cont struct{ fn func() any }
	var goRec func(acc any, currentLen int, xs []any) any
	goRec = func(acc any, currentLen int, xs []any) any {
		if currentLen == 0 {
			return acc
		}
		last := xs[currentLen-1]
		return &cont{fn: func() any { return goRec(buildFrom(last, acc), currentLen-1, xs) }}
	}
	return func(array any) any {
		arr := array.([]any)
		acc := mapf(finalCell).(func(any) any)(f(arr[len(arr)-1]))
		result := goRec(acc, len(arr)-1, arr)
		for {
			if c, ok := result.(*cont); ok {
				result = c.fn()
			} else {
				break
			}
		}
		return mapf(listToArray).(func(any) any)(result)
	}
}

// ---------------------------------------------------------------------------
// Data.String.* (all string ops work on Go RUNES = codepoints. This matches JS
// for ASCII/BMP and diverges for astral chars -- JS counts UTF-16 code units --
// exactly the inherited ASTRAL ledger. CodeUnits index results are converted
// from byte to rune indices so they stay codepoint-consistent.)
// ---------------------------------------------------------------------------

// byte offset -> rune index within s.
func _runeIndexOf(s string, byteOff int) int { return len([]rune(s[:byteOff])) }

// Data.String.Common
var Data_String_Common_toLower any = func(s any) any { return strings.ToLower(s.(string)) }
var Data_String_Common_toUpper any = func(s any) any { return strings.ToUpper(s.(string)) }
var Data_String_Common_trim any = func(s any) any { return strings.TrimSpace(s.(string)) }
var Data_String_Common_joinWith any = func(sep any) any {
	return func(xs any) any {
		arr := xs.([]any)
		parts := make([]string, len(arr))
		for i, x := range arr {
			parts[i] = x.(string)
		}
		return strings.Join(parts, sep.(string))
	}
}
var Data_String_Common_split any = func(sep any) any {
	return func(s any) any {
		parts := strings.Split(s.(string), sep.(string))
		out := make([]any, len(parts))
		for i, p := range parts {
			out[i] = p
		}
		return out
	}
}
var Data_String_Common_replace any = func(s1 any) any {
	return func(s2 any) any {
		return func(s3 any) any {
			return strings.Replace(s3.(string), s1.(string), s2.(string), 1)
		}
	}
}
var Data_String_Common_replaceAll any = func(s1 any) any {
	return func(s2 any) any {
		return func(s3 any) any {
			return strings.ReplaceAll(s3.(string), s1.(string), s2.(string))
		}
	}
}
var Data_String_Common__localeCompare any = func(lt any) any {
	return func(eq any) any {
		return func(gt any) any {
			return func(s1 any) any {
				return func(s2 any) any {
					switch strings.Compare(s1.(string), s2.(string)) {
					case -1:
						return lt
					case 1:
						return gt
					default:
						return eq
					}
				}
			}
		}
	}
}

// Data.String.Unsafe
var Data_String_Unsafe_charAt any = func(i any) any {
	return func(s any) any {
		rs := []rune(s.(string))
		idx := i.(int)
		if idx >= 0 && idx < len(rs) {
			return string(rs[idx])
		}
		panic("Data.String.Unsafe.charAt: Invalid index.")
	}
}

// Data.String.CodeUnits
var Data_String_CodeUnits_fromCharArray any = func(a any) any {
	var sb strings.Builder
	for _, c := range a.([]any) {
		sb.WriteString(c.(string))
	}
	return sb.String()
}
var Data_String_CodeUnits_toCharArray any = func(s any) any {
	rs := []rune(s.(string))
	out := make([]any, len(rs))
	for i, r := range rs {
		out[i] = string(r)
	}
	return out
}
var Data_String_CodeUnits_singleton any = func(c any) any { return c }
var Data_String_CodeUnits_length any = func(s any) any { return len([]rune(s.(string))) }
var Data_String_CodeUnits__charAt any = func(just any) any {
	return func(nothing any) any {
		return func(i any) any {
			return func(s any) any {
				rs := []rune(s.(string))
				idx := i.(int)
				if idx >= 0 && idx < len(rs) {
					return just.(func(any) any)(string(rs[idx]))
				}
				return nothing
			}
		}
	}
}
var Data_String_CodeUnits__toChar any = func(just any) any {
	return func(nothing any) any {
		return func(s any) any {
			if len([]rune(s.(string))) == 1 {
				return just.(func(any) any)(s)
			}
			return nothing
		}
	}
}
var Data_String_CodeUnits_countPrefix any = func(p any) any {
	return func(s any) any {
		rs := []rune(s.(string))
		pf := p.(func(any) any)
		i := 0
		for i < len(rs) && pf(string(rs[i])).(bool) {
			i++
		}
		return i
	}
}
var Data_String_CodeUnits__indexOf any = func(just any) any {
	return func(nothing any) any {
		return func(x any) any {
			return func(s any) any {
				bi := strings.Index(s.(string), x.(string))
				if bi == -1 {
					return nothing
				}
				return just.(func(any) any)(_runeIndexOf(s.(string), bi))
			}
		}
	}
}
var Data_String_CodeUnits__indexOfStartingAt any = func(just any) any {
	return func(nothing any) any {
		return func(x any) any {
			return func(startAt any) any {
				return func(s any) any {
					rs := []rune(s.(string))
					sa := startAt.(int)
					if sa < 0 || sa > len(rs) {
						return nothing
					}
					sub := string(rs[sa:])
					bi := strings.Index(sub, x.(string))
					if bi == -1 {
						return nothing
					}
					return just.(func(any) any)(sa + _runeIndexOf(sub, bi))
				}
			}
		}
	}
}
var Data_String_CodeUnits__lastIndexOf any = func(just any) any {
	return func(nothing any) any {
		return func(x any) any {
			return func(s any) any {
				bi := strings.LastIndex(s.(string), x.(string))
				if bi == -1 {
					return nothing
				}
				return just.(func(any) any)(_runeIndexOf(s.(string), bi))
			}
		}
	}
}
var Data_String_CodeUnits__lastIndexOfStartingAt any = func(just any) any {
	return func(nothing any) any {
		return func(x any) any {
			return func(startAt any) any {
				return func(s any) any {
					rs := []rune(s.(string))
					xs := x.(string)
					sa := startAt.(int)
					if sa > len(rs) {
						sa = len(rs)
					}
					for pos := sa; pos >= 0; pos-- {
						if strings.HasPrefix(string(rs[pos:]), xs) {
							return just.(func(any) any)(pos)
						}
					}
					return nothing
				}
			}
		}
	}
}
var Data_String_CodeUnits_take any = func(n any) any {
	return func(s any) any {
		rs := []rune(s.(string))
		k := n.(int)
		if k < 0 {
			k = 0
		} else if k > len(rs) {
			k = len(rs)
		}
		return string(rs[:k])
	}
}
var Data_String_CodeUnits_drop any = func(n any) any {
	return func(s any) any {
		rs := []rune(s.(string))
		k := n.(int)
		if k < 0 {
			k = 0
		} else if k > len(rs) {
			k = len(rs)
		}
		return string(rs[k:])
	}
}
var Data_String_CodeUnits_slice any = func(b any) any {
	return func(e any) any {
		return func(s any) any {
			rs := []rune(s.(string))
			n := len(rs)
			bb, ee := b.(int), e.(int)
			if bb < 0 {
				if bb += n; bb < 0 {
					bb = 0
				}
			} else if bb > n {
				bb = n
			}
			if ee < 0 {
				if ee += n; ee < 0 {
					ee = 0
				}
			} else if ee > n {
				ee = n
			}
			if bb > ee {
				return ""
			}
			return string(rs[bb:ee])
		}
	}
}
var Data_String_CodeUnits_splitAt any = func(i any) any {
	return func(s any) any {
		rs := []rune(s.(string))
		k := i.(int)
		if k < 0 {
			k = 0
		} else if k > len(rs) {
			k = len(rs)
		}
		return map[string]any{"before": string(rs[:k]), "after": string(rs[k:])}
	}
}

// Data.String.CodePoints (codepoint = rune-as-int; the fallback arg is ignored,
// matching the JS branch that uses native codePointAt/iterator/fromCodePoint).
var Data_String_CodePoints__unsafeCodePointAt0 any = func(fallback any) any {
	return func(str any) any { return int([]rune(str.(string))[0]) }
}
var Data_String_CodePoints__codePointAt any = func(fallback any) any {
	return func(just any) any {
		return func(nothing any) any {
			return func(ucp0 any) any {
				return func(index any) any {
					return func(str any) any {
						rs := []rune(str.(string))
						i := index.(int)
						if i < 0 || i >= len(rs) {
							return nothing
						}
						return just.(func(any) any)(int(rs[i]))
					}
				}
			}
		}
	}
}
var Data_String_CodePoints__countPrefix any = func(fallback any) any {
	return func(ucp0 any) any {
		return func(pred any) any {
			return func(str any) any {
				pf := pred.(func(any) any)
				count := 0
				for _, r := range []rune(str.(string)) {
					if !pf(int(r)).(bool) {
						return count
					}
					count++
				}
				return count
			}
		}
	}
}
var Data_String_CodePoints__fromCodePointArray any = func(singleton any) any {
	return func(cps any) any {
		var sb strings.Builder
		for _, c := range cps.([]any) {
			sb.WriteRune(rune(c.(int)))
		}
		return sb.String()
	}
}
var Data_String_CodePoints__singleton any = func(fallback any) any {
	return func(cp any) any { return string(rune(cp.(int))) }
}
var Data_String_CodePoints__take any = func(fallback any) any {
	return func(n any) any {
		return func(str any) any {
			rs := []rune(str.(string))
			k := n.(int)
			if k < 0 {
				k = 0
			} else if k > len(rs) {
				k = len(rs)
			}
			return string(rs[:k])
		}
	}
}
var Data_String_CodePoints__toCodePointArray any = func(fallback any) any {
	return func(ucp0 any) any {
		return func(str any) any {
			rs := []rune(str.(string))
			out := make([]any, len(rs))
			for i, r := range rs {
				out[i] = int(r)
			}
			return out
		}
	}
}

// ---------------------------------------------------------------------------
// Partial / Partial.Unsafe
// ---------------------------------------------------------------------------

// _crashWith(msg) throws; mirror as panic. _unsafePartial(f) calls f() -- in the
// curried repr the Partial constraint dict is the (unused) argument, so pass nil.
var Partial__crashWith any = func(msg any) any { panic(msg.(string)) }
var Partial_Unsafe__unsafePartial any = func(f any) any { return f.(func(any) any)(nil) }

// ---------------------------------------------------------------------------
// Trivial spike shims (kept so spike/finish-gate.sh still runs end-to-end)
// ---------------------------------------------------------------------------

var Trivial_goLog any = func(s any) any {
	return func() any {
		fmt.Println(s.(string))
		return nil
	}
}
var Trivial_goConcat any = func(a any) any { return func(b any) any { return a.(string) + b.(string) } }
var Trivial_goIntToString any = func(n any) any { return fmt.Sprintf("%d", n.(int)) }
var Trivial_goAdd any = func(a any) any { return func(b any) any { return a.(int) + b.(int) } }
var Trivial_goMul any = func(a any) any { return func(b any) any { return a.(int) * b.(int) } }
var Trivial_pureEffect any = func(a any) any { return func() any { return a } }
var Trivial_bindEffect any = func(m any) any {
	return func(k any) any {
		return func() any {
			a := m.(func() any)()
			return k.(func(any) any)(a).(func() any)()
		}
	}
}

// ---------------------------------------------------------------------------
// backend-go PrimOp / branch / effect helper ABI
//
// codegen lowers every BackendSyntax PrimOp and Branch test to one of these
// `any`-taking helpers (see Codegen/Go.purs). They assert operand types
// INTERNALLY, so a concretely-typed operand (a literal, or another helper's
// result) and a boxed `any` operand emit identically -- Go forbids `.(T)` on a
// concrete type, which inline assertions would hit on literal operands.
// Semantics match the Phase 1 prelude shims, so the INT64/ASTRAL divergence
// ledger is inherited verbatim (int arithmetic does NOT int32-wrap; bit ops do).
// ---------------------------------------------------------------------------

func _truthy(x any) bool { return x.(bool) }

func _isTag(v any, tag string) bool { return v.(V).Tag == tag }

func _not(a any) any    { return !a.(bool) }
func _and(a, b any) any { return a.(bool) && b.(bool) }
func _or(a, b any) any  { return a.(bool) || b.(bool) }

func _intNeg(a any) any      { return -a.(int) }
func _numNeg(a any) any      { return -a.(float64) }
func _bitNot(a any) any      { return _toInt32(^a.(int)) }
func _arrayLength(a any) any { return len(a.([]any)) }

func _intAdd(a, b any) any { return a.(int) + b.(int) }
func _intSub(a, b any) any { return a.(int) - b.(int) }
func _intMul(a, b any) any { return a.(int) * b.(int) }
func _intDiv(a, b any) any {
	x, y := a.(int), b.(int)
	if y == 0 {
		return 0
	}
	if y > 0 {
		return _floorDivPos(x, y)
	}
	return -_floorDivPos(x, -y)
}

func _numAdd(a, b any) any { return a.(float64) + b.(float64) }
func _numSub(a, b any) any { return a.(float64) - b.(float64) }
func _numMul(a, b any) any { return a.(float64) * b.(float64) }
func _numDiv(a, b any) any { return a.(float64) / b.(float64) }

func _intEq(a, b any) any { return a.(int) == b.(int) }
func _intNe(a, b any) any { return a.(int) != b.(int) }
func _intGt(a, b any) any { return a.(int) > b.(int) }
func _intGe(a, b any) any { return a.(int) >= b.(int) }
func _intLt(a, b any) any { return a.(int) < b.(int) }
func _intLe(a, b any) any { return a.(int) <= b.(int) }

func _numEq(a, b any) any { return a.(float64) == b.(float64) }
func _numNe(a, b any) any { return a.(float64) != b.(float64) }
func _numGt(a, b any) any { return a.(float64) > b.(float64) }
func _numGe(a, b any) any { return a.(float64) >= b.(float64) }
func _numLt(a, b any) any { return a.(float64) < b.(float64) }
func _numLe(a, b any) any { return a.(float64) <= b.(float64) }

func _strEq(a, b any) any { return a.(string) == b.(string) }
func _strNe(a, b any) any { return a.(string) != b.(string) }
func _strGt(a, b any) any { return a.(string) > b.(string) }
func _strGe(a, b any) any { return a.(string) >= b.(string) }
func _strLt(a, b any) any { return a.(string) < b.(string) }
func _strLe(a, b any) any { return a.(string) <= b.(string) }

// Char is a single-rune string, so char ordering is string ordering.
func _charEq(a, b any) any { return _strEq(a, b) }
func _charNe(a, b any) any { return _strNe(a, b) }
func _charGt(a, b any) any { return _strGt(a, b) }
func _charGe(a, b any) any { return _strGe(a, b) }
func _charLt(a, b any) any { return _strLt(a, b) }
func _charLe(a, b any) any { return _strLe(a, b) }

func _boolEq(a, b any) any { return a.(bool) == b.(bool) }
func _boolNe(a, b any) any { return a.(bool) != b.(bool) }
func _boolGt(a, b any) any { return _b2i(a.(bool)) > _b2i(b.(bool)) }
func _boolGe(a, b any) any { return _b2i(a.(bool)) >= _b2i(b.(bool)) }
func _boolLt(a, b any) any { return _b2i(a.(bool)) < _b2i(b.(bool)) }
func _boolLe(a, b any) any { return _b2i(a.(bool)) <= _b2i(b.(bool)) }

func _bitAnd(a, b any) any { return _toInt32(a.(int) & b.(int)) }
func _bitOr(a, b any) any  { return _toInt32(a.(int) | b.(int)) }
func _bitXor(a, b any) any { return _toInt32(a.(int) ^ b.(int)) }
func _shl(a, b any) any    { return int(int32(uint32(a.(int)) << uint(b.(int)&31))) }
func _shr(a, b any) any    { return int(int32(uint32(a.(int))) >> uint(b.(int)&31)) }
func _zshr(a, b any) any   { return int(uint32(a.(int)) >> uint(b.(int)&31)) }

func _strAppend(a, b any) any  { return a.(string) + b.(string) }
func _arrayIndex(a, i any) any { return a.([]any)[i.(int)] }

// Native int division with PureScript semantics: div-by-zero is 0 (the JS
// foreign returns 0), truncation toward zero (Go `/` already does). Used by the
// unboxed-int-loop codegen where `/` would otherwise panic on a zero divisor.
func _intDivI(a, b int) int {
	if b == 0 {
		return 0
	}
	return a / b
}

// Immutable record update: copy the base record, overwrite the given fields.
func _recordUpdate(base any, updates map[string]any) any {
	m := base.(map[string]any)
	n := make(map[string]any, len(m))
	for k, v := range m {
		n[k] = v
	}
	for k, v := range updates {
		n[k] = v
	}
	return n
}

// Effect.Exception: an Error is map[string]any{"message","name"}; throwException
// panics with it, catchException recovers (wrapping a non-Error panic like the JS
// shim's `new Error(e.toString())`). Pulled into the build transitively by
// transformers (Control.Monad.Error.Class).
func _exnError(msg any) any { return map[string]any{"message": msg, "name": "Error"} }

var Effect_Exception_error any = func(msg any) any { return _exnError(msg) }
var Effect_Exception_errorWithName any = func(msg any) any {
	return func(nm any) any { return map[string]any{"message": msg, "name": nm} }
}
var Effect_Exception_message any = func(e any) any { return e.(map[string]any)["message"] }
var Effect_Exception_name any = func(e any) any {
	if n, ok := e.(map[string]any)["name"]; ok && n != nil {
		return n
	}
	return "Error"
}
var Effect_Exception_showErrorImpl any = func(e any) any {
	return "Error: " + fmt.Sprintf("%v", e.(map[string]any)["message"])
}
var Effect_Exception_stackImpl any = func(_just any) any {
	return func(nothing any) any {
		return func(_e any) any { return nothing } // no stack in our representation
	}
}
var Effect_Exception_throwException any = func(e any) any {
	return func() any { panic(e) }
}
var Effect_Exception_catchException any = func(c any) any {
	return func(t any) any {
		return func() (result any) {
			defer func() {
				if r := recover(); r != nil {
					var errVal any
					if m, ok := r.(map[string]any); ok && m["message"] != nil {
						errVal = r
					} else {
						errVal = _exnError(fmt.Sprintf("%v", r))
					}
					result = c.(func(any) any)(errVal).(func() any)()
				}
			}()
			return t.(func() any)()
		}
	}
}

// Effect / ST ref cells share Phase 1's representation: map[string]any{"value"}.
func _refNew(v any) any  { return map[string]any{"value": v} }
func _refRead(r any) any { return r.(map[string]any)["value"] }
func _refWrite(r, v any) any {
	r.(map[string]any)["value"] = v
	return nil
}

// _runEffect forces an `Effect a` (a `func() any` thunk) to its result.
func _runEffect(x any) any { return x.(func() any)() }

func _fail(msg string) any  { panic(msg) }
func _todo(what string) any { panic("backend-go: unimplemented IR node: " + what) }

// ---------------------------------------------------------------------------
// Additional foreign shims the whole-program optimizer build references but the
// 10-module Phase 1 corpus never exercised. Correct impls for the reachable/easy
// ones; panic-stubs for foreigns no corpus test calls (Regex, Number.Format) so
// the corpus COMPILES -- a stub only fires if actually executed.
// ---------------------------------------------------------------------------

// JS globals referenced by Data.Number (and Test.Numbers).
var Infinity any = math.Inf(1)
var NaN any = math.NaN()

// Non-finite Number literals (codegen emits these; runtime.go owns `math`).
var _posInf any = math.Inf(1)
var _negInf any = math.Inf(-1)
var _nan any = math.NaN()

var Data_Reflectable_unsafeCoerce any = func(x any) any { return x }

// Console extras (all Effect Unit; clear takes no arg, the rest take a label).
var Effect_Console_clear any = func() any { return nil }
var Effect_Console_groupCollapsed any = func(s any) any { return func() any { return nil } }
var Effect_Console_time any = func(s any) any { return func() any { return nil } }
var Effect_Console_timeEnd any = func(s any) any { return func() any { return nil } }
var Effect_Console_timeLog any = func(s any) any { return func() any { return nil } }

// Data.Lazy: defer(\_ -> a) builds a memoized Lazy a; force evaluates it.
var Data_Lazy_defer_ any = func(f any) any {
	var done bool
	var val any
	return func() any {
		if !done {
			val = f.(func(any) any)(nil)
			done = true
		}
		return val
	}
}
var Data_Lazy_force any = func(l any) any { return l.(func() any)() }

// Data.Show.Generic.intercalate :: String -> Array String -> String
var Data_Show_Generic_intercalate any = func(sep any) any {
	return func(xs any) any {
		arr := xs.([]any)
		parts := make([]string, len(arr))
		for i, s := range arr {
			parts[i] = s.(string)
		}
		return strings.Join(parts, sep.(string))
	}
}

// Data.Array.ST.Partial: unsafe peek/poke. STArray is *[]any (Phase 1 rep).
var Data_Array_ST_Partial_peekImpl any = func(i any) any {
	return func(arr any) any {
		return func() any { return (*arr.(*[]any))[i.(int)] }
	}
}
var Data_Array_ST_Partial_pokeImpl any = func(i any) any {
	return func(x any) any {
		return func(arr any) any {
			return func() any {
				(*arr.(*[]any))[i.(int)] = x
				return nil
			}
		}
	}
}

// Number formatting + Regex: no corpus test exercises these; stub so the whole
// corpus compiles. Replace with faithful impls when a test reaches them.
var Data_Number_Format_toExponentialNative any = func(d any) any {
	return func(num any) any {
		return _jsExponent(strconv.FormatFloat(num.(float64), 'e', d.(int), 64))
	}
}
var Data_Number_Format_toFixedNative any = func(d any) any {
	return func(num any) any {
		return strconv.FormatFloat(num.(float64), 'f', d.(int), 64)
	}
}
var Data_Number_Format_toPrecisionNative any = func(d any) any {
	return func(num any) any {
		// JS toPrecision picks fixed or exponential by the decimal exponent:
		// exponential iff e < -6 or e >= precision. Go's 'g' uses a different
		// rule, so decide here and format explicitly.
		f := num.(float64)
		p := d.(int)
		if f == 0 {
			return _jsExponent(strconv.FormatFloat(0, 'f', p-1, 64))
		}
		e := int(math.Floor(math.Log10(math.Abs(f))))
		if e < -6 || e >= p {
			return _jsExponent(strconv.FormatFloat(f, 'e', p-1, 64))
		}
		return strconv.FormatFloat(f, 'f', p-1-e, 64)
	}
}
var Data_String_Regex__match any = func(_ any) any { panic("backend-go TODO: Data.String.Regex.match") }
var Data_String_Regex__replaceBy any = func(_ any) any { panic("backend-go TODO: Data.String.Regex.replaceBy") }
var Data_String_Regex__search any = func(_ any) any { panic("backend-go TODO: Data.String.Regex.search") }
var Data_String_Regex_flagsImpl any = func(_ any) any { panic("backend-go TODO: Data.String.Regex.flagsImpl") }
var Data_String_Regex_regexImpl any = func(_ any) any { panic("backend-go TODO: Data.String.Regex.regexImpl") }
var Data_String_Regex_showRegexImpl any = func(_ any) any { panic("backend-go TODO: Data.String.Regex.showRegexImpl") }

// ---------------------------------------------------------------------------
// Test.Assert — the corpus's assertion module. Added to THIS lane 2026-07-31;
// it had been added to psgo's runtime/prelude.go only, so every optimizer-lane
// program importing Test.Assert failed to link. Errors here are the lane's own
// map[string]any representation (_exnError), not psgo's PSError.
//
// NB checkThrows recovers a panic, which in Go does NOT include stack
// exhaustion ("goroutine stack exceeded" is a fatal, unrecoverable runtime
// error). Corpus tests that assert a deep non-tail recursion THROWS therefore
// cannot pass on Go by exhausting the real stack — see the TCO analysis in
// docs/kb/research/what-the-other-backends-know.md.
var Test_Assert_assertImpl any = func(message any) any {
	return func(success any) any {
		return func() any {
			if b, ok := success.(bool); !ok || !b {
				panic(_exnError(message))
			}
			return nil
		}
	}
}

var Test_Assert_checkThrows any = func(fn any) any {
	return func() (result any) {
		defer func() {
			if r := recover(); r != nil {
				result = true
			}
		}()
		fn.(func(any) any)(nil)
		return false
	}
}

// Two foreigns the oracle lane (runtime/prelude.go) had and this one did not.
// Found 2026-07-31 by diffing the two runtimes' symbol sets — the drift was
// only these two, which is worth knowing: the lanes are otherwise in step.
var Data_Number_Format_toString any = func(num any) any {
	return _jsNumToString(num.(float64))
}

var Effect_Exception_errorWithCause any = func(msg any) any {
	return func(cause any) any {
		return map[string]any{"message": msg, "name": "Error", "cause": cause}
	}
}

// Ported from the oracle lane 2026-07-31 (Test.Formatting): JS renders an
// exponent with a sign and no leading zeros ("1e+21"); Go emits "1e+21" only
// after trimming, so normalise here to keep the two lanes byte-identical.
func _jsExponent(s string) string {
	i := strings.IndexAny(s, "eE")
	if i < 0 {
		return s
	}
	mantissa, exp := s[:i], s[i+1:]
	sign := "+"
	if len(exp) > 0 && (exp[0] == '+' || exp[0] == '-') {
		sign = string(exp[0])
		exp = exp[1:]
	}
	exp = strings.TrimLeft(exp, "0")
	if exp == "" {
		exp = "0"
	}
	return mantissa + "e" + sign + exp
}
